//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SFXEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MODELDIALOGBAR              103
#define IDR_MAINFRAME                   128
#define IDR_SFXEDITYPE                  129
#define IDD_WORKPANEL                   130
#define IDD_FRAMEPANEL                  131
#define IDD_1OBJ                        133
#define IDD_1TEX                        135
#define IDD_ADDPART                     136
#define IDR_DATA1                       139
#define IDR_POPUPMENU                   140
#define IDD_EDIT_DIALOG                 141
#define IDR_POPUPMENU2                  142
#define IDD_NAME_DIALOG                 143
#define IDD_MODEL_DIALOG                144
#define IDD_INFO_DIALOG                 147
#define IDC_WORKTAB                     1003
#define IDC_LIST1                       1004
#define IDC_TEXLIST                     1004
#define IDC_OBJLIST                     1005
#define IDC_X                           1011
#define IDC_Y                           1012
#define IDC_Z                           1013
#define IDC_SX                          1014
#define IDC_SY                          1015
#define IDC_A                           1016
#define IDC_ANGX                        1017
#define IDC_RADIOBILL                   1018
#define IDC_RADIOBOTTOM                 1019
#define IDC_RADIOPOLE                   1020
#define IDC_RADIONORMAL                 1021
#define IDC_SZ                          1022
#define IDC_ANGY                        1023
#define IDC_ANGZ                        1024
#define IDC_PROTX                       1025
#define IDC_PROTY                       1026
#define IDC_PROTZ                       1027
#define IDC_RADIOBLEND                  1028
#define IDC_RADIOGLOW                   1029
#define IDC_PCREATE                     1030
#define IDC_PCREATENUM                  1031
#define IDC_TEXFRAME                    1032
#define IDC_TEXLOOP                     1033
#define IDC_PAPPEAR                     1034
#define IDC_PKEEP                       1035
#define IDC_PDISAPPEAR                  1036
#define IDC_PPOSVAR                     1037
#define IDC_PPOSVARY                    1038
#define IDC_PYLOW                       1040
#define IDC_PYHIGH                      1041
#define IDC_PXZLOW                      1042
#define IDC_PXZHIGH                     1043
#define IDC_PACCELX                     1044
#define IDC_PACCELY                     1045
#define IDC_PACCELZ                     1046
#define IDC_PSCALEX                     1047
#define IDC_PSCALEY                     1048
#define IDC_PSCALEZ                     1049
#define IDC_PSCALESPEEDX                1050
#define IDC_PSCALESPEEDY                1051
#define IDC_PSCALESPEEDZ                1052
#define IDC_XSCALREPEATLOW              1053
#define IDC_XSCALREPEATHIGH             1054
#define IDC_PARTICLE_ROT_X_LOW          1055
#define IDC_PARTICLE_ROT_X_HIGH         1056
#define IDC_PARTICLE_ROT_Y_LOW          1057
#define IDC_PARTICLE_ROT_Y_HIGH         1058
#define IDC_PARTICLE_ROT_Z_LOW          1059
#define IDC_PARTICLE_ROT_Z_HIGH         1060
#define IDC_PSCALEENDX                  1061
#define IDC_PSCALEENDY                  1062
#define IDC_PSCALEENDZ                  1063
#define IDC_YSCALREPEATLOW              1064
#define IDC_YSCALREPEATHIGH             1065
#define IDC_ZSCALREPEATLOW              1066
#define IDC_ZSCALREPEATHIGH             1067
#define IDC_BUTTONTEX                   1070
#define IDC_BUTTONTEXNULL               1071
#define IDC_BUTTONSAVESFX               1072
#define IDC_BUTTONLOADSFX               1073
#define IDC_BUTTONQLOADSFX              1074
#define IDC_BUTTONQSAVESFX              1075
#define IDC_BUTTONLOADSFX2              1076
#define IDC_RADIO_DAP_BILL              1079
#define IDC_RADIO_DAP_PARTICLE          1080
#define IDC_RADIO_DAP_MESH              1081
#define IDC_RADIO_DAP_CUSTOMMESH        1082
#define IDC_CHECK1                      1095
#define IDC_CHECK2                      1096
#define IDC_SCAL_REPEAT_CHECK           1096
#define IDC_CHECK3                      1097
#define IDC_EDIT1                       1097
#define IDC_PRT_REPEAT_CHECK2           1097
#define IDC_CHECK4                      1098
#define IDC_CHECK5                      1099
#define IDC_BUTTON1                     1099
#define IDC_CHECK6                      1100
#define IDC_BUTTON2                     1100
#define IDC_CHECK7                      1101
#define IDC_BUTTON3                     1101
#define IDC_MODELROTY                   1101
#define IDC_CHECK8                      1102
#define IDC_BGCOLOREDIT                 1102
#define IDC_CHECK9                      1103
#define IDC_MODELROTX                   1103
#define IDC_LIST2                       1103
#define IDC_CHECK10                     1104
#define IDC_MODELROTZ                   1104
#define IDC_CHECK11                     1105
#define IDC_CHECK12                     1106
#define ID_FILE_OPENSFX                 32771
#define ID_FILE_SAVESFX                 32772
#define ID_OPENSFX                      32773
#define ID_SAVESFX                      32774
#define ID_EDIT_PLAY                    32775
#define ID_EDIT_STOP                    32776
#define ID_POPUPMENU                    32777
#define ID_VIEWCHRMODEL                 32780
#define ID_VIEWAXIS                     32781
#define ID_VALUTCHANGE                  32784
#define ID_NAMECHANGE                   32785
#define ID_MODEL_SETTING                32788
#define ID_VIEWBG                       32789
#define ID_FLAT                         32792
#define ID_INFO                         32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
