#ifndef __RESOURCE_H
#define __RESORUCE_H

// Applet Id
#define APP_APPLET0                     100
#define APP_APPLET1                     101
#define APP_APPLET2                     102
#define APP_APPLET3                     103
#define APP_APPLET4                     104
#define APP_APPLET5                     105
#define APP_APPLET6                     106
#define APP_APPLET7                     107
#define APP_APPLET8                     108
#define APP_APPLET9                     109
#define APP_APPLET10                    110
#define APP_APPLET11                    111
#define APP_ADMINGGG                    112
#define APP_CONFIRM_BUY                 113
#define APP_CONFIRM_SELL                114
#define APP_GOLD                        115
#define APP_TRADE_GOLD                  116
#define APP_APPLET12                    117
#define APP_DELETE_CHAR                 118
#define APP_APPLET13                    119
#define APP_REVIVAL                     120
#define APP_TIP                         121
#define APP_APPLET14                    122
#define APP_APPLET15                    123
#define APP_APPLET16                    124
#define APP_APPLET17                    125
#define APP_APPLET18                    126
#define APP_APPLET19                    127
#define APP_MESSAGEBOX_OK               128
#define APP_APPLET20                    129
#define APP_MESSAGEBOX_OK_CANCEL        130
#define APP_APPLET21                    131
#define APP_APPLET22                    132
#define APP_APPLET23                    133
#define APP_APPLET24                    134
#define APP_APPLET25                    135
#define APP_APPLET26                    136
#define APP_SAMPLE                      137
#define APP_APPLET27                    138
#define APP_APPLET28                    139
#define APP_APPLET29                    140
#define APP_ADMIN_CREATEITEM            141
#define APP_APPLET30                    142
#define APP_APPLET31                    143
#define APP_CHARACTER2                  144
#define APP_STATUS                      145
#define APP_APPLET32                    146
#define APP_APPLET33                    147
#define APP_APPLET34                    148
#define APP_APPLET35                    149
#define APP_EXTRA_CAPTURE               150
#define APP_APPLET36                    151
#define APP_QUICKLIST                   152
#define APP_APPLET37                    153
#define APP_APPLET38                    154
#define APP_ADD_PLAYER                  155
#define APP_APPLET39                    156
#define APP_COMMUNICATION_INSMSG        157
#define APP_APPLET40                    158
#define APP_OPTION_ETC                  159
#define APP_APPLET41                    160
#define APP_APPLET42                    161
#define APP_APPLET43                    162
#define APP_OPTION_WINDOW               163
#define APP_OPTION_SLANG                164
#define APP_APPLET44                    165
#define APP_COMMAND                     166
#define APP_APPLET45                    167
#define APP_APPLET46                    168
#define APP_QUEST                       169
#define APP_APPLET47                    170
#define APP_APPLET48                    171
#define APP_MOTION                      172
#define APP_APPLET49                    173
#define APP_ADMIN_CREATEMONSTER         174
#define APP_APPLET50                    175
#define APP_ADMIN_EVENT_STATUS          176
#define APP_APPLET51                    177
#define APP_ADMIN_PLAYER_CONTROL        178
#define APP_APPLET52                    179
#define APP_ADMIN_STATUS                180
#define APP_APPLET53                    181
#define APP_ADMIN_INDIRECT_TALK         182
#define APP_APPLET54                    183
#define APP_ADMIN_EVENT_MANAGER         184
#define APP_APPLET55                    185
#define APP_ADMIN_GIVE_ITEM             186
#define APP_APPLET56                    187
#define APP_ADMIN_EVENT_INSTANT         188
#define APP_ADMIN_EVENT_LAUNCHER        189
#define APP_APPLET57                    190
#define APP_ADMIN_EVENT_MAKER           191
#define APP_APPLET58                    192
#define APP_ADMIN_BALANCE               193
#define APP_APPLET59                    194
#define APP_PARTY                       195
#define APP_APPLET60                    196
#define APP_PARTY_INFO                  197
#define APP_APPLET61                    198
#define APP_PARTY_SKILL                 199
#define APP_APPLET62                    200
#define APP_DUEL_CONFIRM                201
#define APP_APPLET63                    202
#define APP_APPLET64                    203
#define APP_BANK                        204
#define APP_APPLET65                    205
#define APP_APPLET66                    206
#define APP_APPLET67                    207
#define APP_NOTICE                      208
#define APP_APPLET68                    209
#define APP_PVP                         210
#define APP_APPLET69                    211
#define APP_OPTIN_GAME                  212
#define APP_OPTION_GAME                 213
#define APP_APPLET70                    214
#define APP_HEL_INSTANT                 215
#define APP_HELP_INSTANT                216
#define APP_APPLET71                    217
#define APP_BALANCE_EXP                 218
#define APP_ADMIN_BALANCE_EXP           219
#define APP_APPLET72                    220
#define APP_MESSANGER                   221
#define APP_MESSENGER                   222
#define APP_MESSAGE                     223
#define APP_INSTANTMSG                  224
#define APP_APPLET73                    225
#define APP_FRIEND_CONFIRM              226
#define APP_APPLET74                    227
#define APP_MAP                         228
#define APP_APPLET75                    229
#define APP_APPLET76                    230
#define APP_VENDOR                      231
#define APP_APPLET77                    232
#define APP_INVITE_COMPANY              233
#define APP_COMPANY_INVITE              234
#define APP_APPLET78                    235
#define APP_COMPANY_NAME                236
#define APP_APPLET79                    237
#define APP_ADD_FRIEND                  238
#define APP_APPLET80                    239
#define APP_CHANGETROUP                 240
#define APP_APPLET81                    241
#define APP_PARTYCHANGENAME             242
#define APP_APPLET82                    243
#define APP_COMPANY_DESTROY             244
#define APP_APPLET83                    245
#define APP_COMPANY                     246
#define APP_APPLET84                    247
#define APP_BANK_PASSWORD               248
#define APP_APPLET85                    249
#define APP_CREDIT                      250
#define APP_APPLET86                    251
#define APP_NOTE                        252
#define APP_APPLET87                    253
#define APP_APPLET88                    254
#define APP_BANK_PASS                   255
#define APP_CONFIRM_BANK                256
#define APP_APPLET89                    257
#define APP_CONFRIM_TRADE               258
#define APP_CONFIRM_TRADE               259
#define APP_APPLET90                    260
#define APP_ABOUT                       261
#define APP_APPLET91                    262
#define APP_DROP_ITEM                   263
#define APP_APPLET92                    264
#define APP_APPLET93                    265
#define APP_CLOSE_EXISTING_CONNECTION   266
#define APP_APPLET94                    267
#define APP_REGVEND                     268
#define APP_APPLET95                    269
#define APP_ADDFRIEND                   270
#define APP_APPLET96                    271
#define APP_BEAUTY_SHOP                 272
#define APP_APPLET97                    273
#define APP_VENDOR_BUY                  274
#define APP_APPLET98                    275
#define APP_REPAIR                      276
#define APP_APPLET99                    277
#define APP_SHOP_EX                     278
#define APP_APPLET100                   279
#define APP_SHOPEX                      280
#define APP_APPLET101                   281
#define APP_CONFIRM_STAT                282
#define APP_APPLET102                   283
#define APP_APPLET103                   284
#define APP_MESSENGER_SEARCH            285
#define APP_APPLET104                   286
#define APP_STATE_CONFIRM               287
#define APP_APPLET105                   288
#define APP_FRIEND_MESSAGE              289
#define APP_APPLET106                   290
#define APP_PTRADE_CONFIRM              291
#define APP_TRADE_CONFIRM               292
#define APP_APPLET107                   293
#define APP_PARTYLEAVE_CONFIRM          294
#define APP_APPLET108                   295
#define APP_PARTYRETIRE_CONFIRM         296
#define APP_APPLET109                   297
#define APP_MESSENGER_NOTE              298
#define APP_APPLET110                   299
#define APP_MESSAGE_NOTE                300
#define APP_APPLET111                   301
#define APP_MESSENGER_EX                302
#define APP_APPLET112                   303
#define APP_MESS                        304
#define APP_APPLET113                   305
#define APP_CONFIRM_BUYEX               306
#define APP_APPLET114                   307
#define APP_CONFIRM_DROP                308
#define APP_DROP_CONFIRM                309
#define APP_APPLET115                   310
#define APP_GUILD_MAINWND               311
#define APP_APPLET116                   312
#define APP_GUILD_NOTICE                313
#define APP_APPLET117                   314
#define APP_GUILD_SETLOGO               315
#define APP_APPLET118                   316
#define APP_GUILD_MEMBER                317
#define APP_APPLET119                   318
#define APP_GUILD_APPELLATION           319
#define APP_APPLET120                   320
#define APP_GUILD_VOTE                  321
#define APP_APPLET121                   322
#define APP_GUILD                       323
#define APP_APPLET122                   324
#define APP_GUILD_TABINFO               325
#define APP_APPLET123                   326
#define APP_GUILD_TABMEMBER             327
#define APP_GUILD_TABVOTE               328
#define APP_GUILD_TABAPPELLATION        329
#define APP_APPLET124                   330
#define APP_APPLET125                   331
#define APP_GUILD_DISMISS               332
#define APP_APPLET126                   333
#define APP_GUILD_DISMISSINFO           334
#define APP_APPLET127                   335
#define APP_GUILD_BANK                  336
#define APP_APPLET128                   337
#define APP_GUILD_PAYCONFIRM            338
#define APP_GUILD_MERIT                 339
#define APP_APPLET129                   340
#define APP_GUILD_VOTESETING            341
#define APP_APPLET130                   342
#define APP_GUILD_TABGUILDWAR           343
#define APP_APPLET131                   344
#define APP_GUILDNAME                   345
#define APP_APPLET132                   346
#define APP_GUILD_INVATE                347
#define APP_APPLET133                   348
#define APP_GUILD_NICKNAME              349
#define APP_APPLET134                   350
#define APP_GUILD_LEAVE                 351
#define APP_APPLET135                   352
#define APP_RANK_MAIN                   353
#define APP_RANK_1TABBEST               354
#define APP_APPLET136                   355
#define APP_RANK_GUILDMAIN              356
#define APP_RANK_GUILDTABBEST           357
#define APP_APPLET137                   358
#define APP_RANK_GUILDTABUNITED         359
#define APP_APPLET138                   360
#define APP_RANK_GUILDTABPENYA          361
#define APP_APPLET139                   362
#define APP_RANK_                       363
#define APP_RANK_WAR                    364
#define APP_APPLET140                   365
#define APP_RANK_WARTABWIN              366
#define APP_APPLET141                   367
#define APP_RANK_WARTABLOSE             368
#define APP_APPLET142                   369
#define APP_RANK_WARTABGIVEUP           370
#define APP_APPLET143                   371
#define APP_RANK_INFO                   372
#define APP_APPLET144                   373
#define APP_RANK_INFOTABLEVEL           374
#define APP_APPLET145                   375
#define APP_RANK_INFOTABOLD             376
#define APP_RANK_INFOTABPLAYTIME        377
#define APP_RANK_GUILD                  378
#define APP_APPLET146                   379
#define APP_GUILD_WAR                   380
#define APP_APPLET147                   381
#define APP_MOTIONEX                    382
#define APP_APPLET148                   383
#define APP_GUILD_WARGIVEUP             384
#define APP_APPLET149                   385
#define APP_GUILD_WARPEACE              386
#define APP_APPLET150                   387
#define APP_GUILD_WARPEACECONFIRM       388
#define APP_APPLET151                   389
#define APP_GUILD_WARREQUEST            390
#define APP_APPLET152                   391
#define APP_UPGRADE_BASE                392
#define APP_APPLET153                   393
#define APP_TEST                        394
#define APP_APPLET154                   395
#define APP_COMMON_BANK                 396
#define APP_APPLET155                   397
#define APP_COMM_ITEM                   398
#define APP_APPLET156                   399
#define APP_WEBBOX                      400
#define APP_APPLET157                   401
#define APP_VENDOREX                    402
#define APP_APPLET158                   403
#define APP_VENDOREX_CHAT               404
#define APP_APPLET159                   405
#define APP_VENDOREX_BUY                406
#define APP_APPLET160                   407
#define APP_VENDOREX_SELL               408
#define APP_APPLET161                   409
#define APP_QUESTITEM_INFO              410
#define APP_APPLET162                   411
#define APP_OPTIONEX                    412
#define APP_APPLET163                   413
#define APP_OPTEX_AV                    414
#define APP_APPLET164                   415
#define APP_OPTEX_ETC                   416
#define APP_APPLET165                   417
#define APP_OPTEX_GAME                  418
#define APP_APPLET166                   419
#define APP_GUIDE                       420
#define APP_APPLET167                   421
#define APP_GUIDE_TEXT                  422
#define APP_APPLET168                   423
#define APP_GUIDE_SELECTION             424
#define APP_APPLET169                   425
#define APP_QUESTDIARY                  426
#define APP_MESSAGEBOX                  500
#define APP_LOGIN                       501
#define APP_SELECT_SERVER               502
#define APP_CREATE_CHAR                 503
#define APP_SELECT_CHAR                 504
#define APP_NAVIGATOR                   1000
#define APP_STATE                       1001
#define APP_EQUIPMENT                   1002
#define APP_INVENTORY                   1003
#define APP_JOB                         1004
#define APP_SKILL                       1005
#define APP_MACRO                       1006
#define APP_STYLE                       1007
#define APP_EMOTION                     1008
#define APP_TRADE                       1009
#define APP_COMMUNITY_FRIEND            1010
#define APP_COMMUNITY_PARTY             1011
#define APP_COMMUNITY_GUILD             1012
#define APP_COMMUNITY_CLUB              1013
#define APP_COMMUNICATION_CHAT          1014
#define APP_COMMUNICATION_MESSAGE       1015
#define APP_COMMUNICATION_EMAIL         1016
#define APP_COMMUNICATION_BBS           1017
#define APP_FIND_PEOPLE                 1020
#define APP_FILD_GUILD                  1021
#define APP_FIND_CLUB                   1022
#define APP_FIND_SHOP                   1023
#define APP_INFO_NOTICE                 1030
#define APP_INFO_EVENT                  1031
#define APP_INFO_VERSION                1032
#define APP_INFO_SCHEDULE               1033
#define APP_HELPER_HELP                 1040
#define APP_HELPER_TIP                  1041
#define APP_HELPER_FAQ                  1042
#define APP_JOIN_VOTE                   1050
#define APP_JOIN_EVENT                  1051
#define APP_OPTION_VIDEO                1060
#define APP_OPTION_SOUND                1061
#define APP_OPTION_MUSIC                1062
#define APP_OPTION_PASSWORD             1063
#define APP_OPTION_MOUSE                1064
#define APP_OPTION_MYINFO               1065
#define APP_OPTION_HOTKEY               1066
#define APP_OPTION_THEME                1067
#define APP_LOGOUT                      1100
#define APP_QUIT                        1101
#define APP_SEQUENCE                    1102
#define APP_APPLET                      2001
#define APP_WORLD                       2002
#define APP_DIALOG                      2003
#define APP_DEBUGINFO                   2004
#define APP_GAUGE                       2005
#define APP_CONTROLTEST                 2007
#define APP_ADMIN                       2008
#define APP_SHOP                        2009
#define APP_CHARACTER                   2010
#define APP_PARTY_CONFIRM               2011
#define APP_TASKBAR800                  2012
#define APP_TASKBAR1024                 2013
#define APP_TASKBAR1280                 2014

// Control Id
#define WIDC_OK                         100
#define WIDC_YES                        100
#define WIDC_OK_YOU                     100
#define WIDC_CANCEL                     101
#define WIDC_INVENTORY                  102
#define WIDC_COST                       122
#define WIDC_EDIT                       125
#define WIDC_GOLD                       143
#define WIDC_PASSWORD                   147
#define WIDC_REVIVAL_TO_LODESTAR        151
#define WIDC_REVIVAL_TO_LODELIGHT       152
#define WIDC_ACCOUNT                    157
#define WIDC_TEXT                       159
#define WIDC_NEXT                       160
#define WIDC_QUIT                       162
#define WIDC_CLOSE                      163
#define WIDC_BACK                       166
#define WIDC_GOLD_NUM                   168
#define WIDC_CREATE                     170
#define WIDC_DELETE                     171
#define WIDC_ACCEPT                     172
#define WIDC_MALE                       175
#define WIDC_FEMALE                     176
#define WIDC_NAME                       177
#define WIDC_HAIRSTYLE_LEFT             179
#define WIDC_HAIRSTYLE_RIGHT            180
#define WIDC_HAIRCOLOR_LEFT             181
#define WIDC_HAIRCOLOR_RIGHT            182
#define WIDC_FACE_LEFT                  183
#define WIDC_FACE_RIGHT                 184
#define WIDC_STATIC                     185
#define WIDC_CONTROL0                   188
#define WIDC_ITEM_NAME                  206
#define WIDC_ITEM_NUM                   211
#define WIDC_ITEM_KIND                  212
#define WIDC_ITEM_SEX                   216
#define WIDC_TERRAIN_LOD_HIGH           241
#define WIDC_TERRAIN_LOD_MID            242
#define WIDC_TERRAIN_LOD_LOW            243
#define WIDC_TREE1                      248
#define WIDC_LIST1                      255
#define WIDC_OBJECT_DISTANT_HIGH        256
#define WIDC_OBJECT_DISTANT_MID         257
#define WIDC_OBJECT_DISTANT_LOW         258
#define WIDC_OBJECT_LOD_HIGH            259
#define WIDC_OBJECT_LOD_MID             260
#define WIDC_OBJECT_LOD_LOW             261
#define WIDC_SHADOW_HIGH                262
#define WIDC_SHADOW_MID                 263
#define WIDC_HEAD                       265
#define WIDC_MACRO_CHAT                 268
#define WIDC_EDITSELL                   286
#define WIDC_SEND                       288
#define WIDC_CHAR_NAME                  318
#define WIDC_CHECK                      326
#define WIDC_CONTROL8                   333
#define WIDC_INTRODUCTION               333
#define WIDC_CONTROL9                   335
#define WIDC_CONTROL10                  336
#define WIDC_REAL_NAME                  336
#define WIDC_REAL_AGE                   337
#define WIDC_CONTROL11                  337
#define WIDC_REAL_GENDER                338
#define WIDC_CONTROL12                  338
#define WIDC_REAL_JOB                   339
#define WIDC_CONTROL13                  339
#define WIDC_CONTROL14                  342
#define WIDC_CHECK_CHAR_NAME            342
#define WIDC_CONTROL15                  343
#define WIDC_CHECK_REAL_NAME            343
#define WIDC_CHECK_REAL_AGE             344
#define WIDC_CONTROL16                  344
#define WIDC_CONTROL17                  346
#define WIDC_CHECK_REAL_GENDER          346
#define WIDC_CONTROL18                  347
#define WIDC_CHECK_REAL_JOB             347
#define WIDC_CONTROL7                   360
#define WIDC_OK_I                       368
#define WIDC_CONTROL4                   370
#define WIDC_CONTROL5                   371
#define WIDC_CONTROL6                   372
#define WIDC_CLEAR                      373
#define WIDC_CONTROL1                   379
#define WIDC_CONTROL2                   380
#define WIDC_CONTROL3                   381
#define WIDC_BUTTON7                    404
#define WIDC_NUM7                       404
#define WIDC_LISTBOX3                   434
#define WIDC_EDIT4                      436
#define WIDC_EDIT5                      437
#define WIDC_EDIT6                      438
#define WIDC_EDIT7                      439
#define WIDC_CHECK10                    475
#define WIDC_CHECK11                    476
#define WIDC_COMBOBOX3                  478
#define WIDC_GUILD_PAY_ROOKIE           481
#define WIDC_STATIC15                   481
#define WIDC_GUILD_PAY_CAPTAIN          483
#define WIDC_STATIC14                   483
#define WIDC_CHECK12                    486
#define WIDC_COMBOBOX4                  488
#define WIDC_COMBOBOX2                  490
#define WIDC_CHECK13                    498
#define WIDC_GROUPBOX5                  513
#define WIDC_NUM5                       515
#define WIDC_BUTTON5                    515
#define WIDC_NUM6                       516
#define WIDC_BUTTON6                    516
#define WIDC_STATIC12                   529
#define WIDC_GUILDNAME                  529
#define WIDC_COMBOBOX5                  530
#define WIDC_CHECK3                     533
#define WIDC_CHECK4                     534
#define WIDC_CHECK5                     535
#define WIDC_CHECK6                     536
#define WIDC_BUTTON4                    545
#define WIDC_NUM4                       545
#define WIDC_CHECK7                     552
#define WIDC_LISTBOX2                   559
#define WIDC_LEAVE                      566
#define WIDC_CHANGE                     567
#define WIDC_GROUPBOX3                  570
#define WIDC_GROUPBOX4                  571
#define WIDC_ITEM_SHARE                 572
#define WIDC_EXP_SHARE                  576
#define WIDC_LEVEL                      584
#define WIDC_EXP                        585
#define WIDC_POINT                      586
#define WIDC_NO                         588
#define WIDC_GRID                       595
#define WIDC_TERRAIN                    596
#define WIDC_LOD_TERRAIN                597
#define WIDC_ANIMATION                  598
#define WIDC_LIGHT                      599
#define WIDC_CAPTURE                    600
#define WIDC_WIREFRAME                  601
#define WIDC_OBJECT                     602
#define WIDC_WATER                      603
#define WIDC_FRAME_SKIP                 604
#define WIDC_WEATHER                    605
#define WIDC_BOUNDBOX                   606
#define WIDC_SKYBOX                     607
#define WIDC_CULLOBJ                    609
#define WIDC_COLLISION                  610
#define WIDC_FOG                        613
#define WIDC_IDSTATE                    614
#define WIDC_HIDE                       615
#define WIDC_ATTRIBUTE                  616
#define WIDC_HOUR                       618
#define WIDC_GROUPBOX2                  620
#define WIDC_EDIT_HOUR                  621
#define WIDC_LOD_OBJ                    622
#define WIDC_UP                         647
#define WIDC_BUTTON3                    648
#define WIDC_DOWN                       648
#define WIDC_NUM3                       648
#define WIDC_VOTE_FINISH                648
#define WIDC_MAX                        648
#define WIDC_CUSTOM4                    659
#define WIDC_CUSTOM5                    660
#define WIDC_CUSTOM6                    661
#define WIDC_SHADOW_LOW                 679
#define WIDC_CONTEXT1                   690
#define WIDC_TEXT2                      690
#define WIDC_BANKGO_1                   692
#define WIDC_CUSTOM2                    692
#define WIDC_LOGO                       692
#define WIDC_BANKGO_2                   693
#define WIDC_CUSTOM3                    693
#define WIDC_CHECK2                     699
#define WIDC_RADIO3                     708
#define WIDC_RADIO_ALL                  708
#define WIDC_GLOWOFF                    708
#define WIDC_RADIO4                     709
#define WIDC_RADIO5                     710
#define WIDC_RADIO6                     711
#define WIDC_RADIO_FEMALE               715
#define WIDC_RADIO2                     715
#define WIDC_GLOWON                     715
#define WIDC_EDIT_COMPANY_NAME          740
#define WIDC_ADD                        742
#define WIDC_FIND                       744
#define WIDC_KINGPIN                    776
#define WIDC_CURRENTMEMBER              777
#define WIDC_MAXMEMBER                  779
#define WIDC_PENYA                      782
#define WIDC_LISTBOX1                   785
#define WIDC_MEMBERLIST                 785
#define WIDC_GUILDPENYAMERIT            787
#define WIDC_GUILDWARLEFTTIME           787
#define WIDC_STATIC11                   787
#define WIDC_EDIT3                      794
#define WIDC_CREDIT                     797
#define WIDC_CHANGE_PASS                809
#define WIDC_VOICEOFF                   819
#define WIDC_RADIO10                    819
#define WIDC_ABOUT                      819
#define WIDC_GUILDWARGUILDNAME          862
#define WIDC_STATIC7                    862
#define WIDC_GUILDLEVEL                 863
#define WIDC_STATIC8                    863
#define WIDC_GUILDWARWIN                863
#define WIDC_STATIC9                    865
#define WIDC_GUILDMASTER                865
#define WIDC_GUILDWARLOSE               865
#define WIDC_STATIC10                   866
#define WIDC_GUILDEXPMERIT              866
#define WIDC_GUILDWARGIVEUP             866
#define WIDC_STATIC4                    867
#define WIDC_CUSTOM1                    870
#define WIDC_BANKGO_0                   870
#define WIDC_NPCPIC                     870
#define WIDC_STATIC5                    872
#define WIDC_TEXT1                      877
#define WIDC_COND1                      877
#define WIDC_SHOUT_ON                   882
#define WIDC_SHOUT_OFF                  883
#define WIDC_MESSENGERJOIN_ON           884
#define WIDC_MESSENGERJOIN_OFF          885
#define WIDC_STATIC6                    886
#define WIDC_RADIO7                     887
#define WIDC_MESSENGER_ON               887
#define WIDC_MESSENGER_OFF              888
#define WIDC_RADIO8                     888
#define WIDC_NUM2                       889
#define WIDC_VOTE_START                 889
#define WIDC_VOTE                       889
#define WIDC_BUTTON2                    889
#define WIDC_MINUS                      889
#define WIDC_EDIT2                      897
#define WIDC_STATIC2                    900
#define WIDC_BANKGOLD_1                 900
#define WIDC_LIST                       908
#define WIDC_CHECK_LEVEL                911
#define WIDC_CHECK1                     912
#define WIDC_EDIT_COST                  914
#define WIDC_GROUPBOX1                  916
#define WIDC_BUTTON_OK                  920
#define WIDC_BUTTON_CANCLE              921
#define WIDC_STATIC_ID                  925
#define WIDC_EDIT_ID                    926
#define WIDC_STATIC_SERVER              927
#define WIDC_COMBOBOX_SERVER            928
#define WIDC_COMBOBOX1                  928
#define WIDC_GUILDBANK_NUM              929
#define WIDC_STATIC1                    929
#define WIDC_BANKGOLD_0                 929
#define WIDC_STATIC_SEX                 929
#define WIDC_RADIO_MALE                 931
#define WIDC_RADIO1                     931
#define WIDC_VOICEON                    931
#define WIDC_VOTE_SETTING               933
#define WIDC_VOTE_CLEAR                 933
#define WIDC_NUM1                       933
#define WIDC_CHAT                       933
#define WIDC_PROLOGUE                   933
#define WIDC_BUTTON1                    933
#define WIDC_PLUS                       933
#define WIDC_BANK_0                     934
#define WIDC_TABCTRL1                   934
#define WIDC_EDIT1                      935
#define WIDC_STATIC3                    936
#define WIDC_BANKGOLD_2                 936
#define WIDC_GUILDNUMBER                963
#define WIDC_GUILD_PAY_MASTER           964
#define WIDC_GUILD_PAY_SUPPORTER        967
#define WIDC_GUILD_PAY_KINGPIN          968
#define WIDC_GUILD_NUM_MASTER           976
#define WIDC_GUILD_NUM_KINGPIN          977
#define WIDC_GUILD_NUM_CAPTAIN          978
#define WIDC_GUILD_NUM_SUPPORTER        979
#define WIDC_GUILD_NUM_ROOKIE           981
#define WIDC_CHECK8                     989
#define WIDC_CHECK9                     990
#define WIDC_CHECK14                    995
#define WIDC_CHECK15                    996
#define WIDC_CHECK16                    997
#define WIDC_CHECK17                    998
#define WIDC_CHECK18                    999
#define WIDC_CHECK19                    1000
#define WIDC_CHECK20                    1001
#define WIDC_CHECK21                    1002
#define WIDC_CHECK22                    1003
#define WIDC_CHECK23                    1004
#define WIDC_CHECK24                    1005
#define WIDC_CHECK25                    1006
#define WIDC_BANK_1                     1008
#define WIDC_BANK_3                     1009
#define WIDC_NUM8                       1021
#define WIDC_NUM9                       1022
#define WIDC_NUM0                       1023
#define WIDC_NUM00                      1024
#define WIDC_NUM000                     1025
#define WIDC_VENMIN                     1030
#define WIDC_VENMAX                     1031
#define WIDC_RADIO16                    1049
#define WIDC_RADIO9                     1051
#define WIDC_RADIO11                    1052

#endif
