#ifndef __MSGHDR_H__
#define __MSGHDR_H__

#pragma once

//	(DWORD)0x00000000	// reserved
#define PACKETTYPE_MYREG	(DWORD)0x00000001
#define PACKETTYPE_PROCSERVER_LIST	(DWORD)0x00000002
#define PACKETTYPE_LOAD_WORLD	(DWORD)0x00000003
#define PACKETTYPE_RECHARGE_IDSTACK		(DWORD)0x00000004
#define	PACKETTYPE_PASSAGE	(DWORD)0x00000005
#define PACKETTYPE_DUPLICATE	(DWORD)0x00000006
#define PACKETTYPE_UNIFY	(DWORD)0x00000007
#define PACKETTYPE_ID	(DWORD)0x00000008
#define PACKETTYPE_ADDID	(DWORD)0x00000009
#define	PACKETTYPE_POLL	(DWORD)0x0000000a
#define	PACKETTYPE_QUERYTICKCOUNT	(DWORD)0x0000000b
#define	PACKETTYPE_ERROR_TEXT	(DWORD)0x0000000d
#define	PACKETTYPE_PLAYERCOUNT	(DWORD)0x0000000f
#define	PACKETTYPE_QUERYSETGUILDNAME	(DWORD)0x00000010
#define	PACKETTYPE_AUTHQUERY	(DWORD)0x00000011
#define	PACKETTYPE_QUERYSETPLAYERNAME	(DWORD)0x00000012
#define	PACKETTYPE_CONN							(DWORD)0x00000013
#define	PACKETTYPE_PING							(DWORD)0x00000014
#define	PACKETTYPE_GET_CLOCK					(DWORD)0x00000015
#define	PACKETTYPE_CLOSE_EXISTING_CONNECTION	(DWORD)0x00000016
#define PACKETTYPE_ONE_HOUR_NOTIFY				(DWORD)0x00000017
#define	PACKETTYPE_KEEP_ALIVE	(DWORD)0x00000018
#define	PACKETTYPE_RUNEQ	(DWORD)0x00000019

#define	PACKETTYPE_QUERYPOSTMAIL		(DWORD)0x0000001a
#define	PACKETTYPE_QUERYREMOVEMAIL		(DWORD)0x0000001b
#define	PACKETTYPE_QUERYGETMAILITEM		(DWORD)0x0000001c
#define	PACKETTYPE_QUERYMAILBOX		(DWORD)0x0000001d
#define	PACKETTYPE_ALLMAIL	(DWORD)0x0000001e
#define	PACKETTYPE_QUERYGETMAILGOLD		(DWORD)0x0000001f
#define	PACKETTYPE_READMAIL		(DWORD)0x00000024

#define	PACKETTYPE_DO_ESCAPE	(DWORD)0x00000020
#define	PACKETTYPE_SETSNOOP		(DWORD)0x00000021
#define	PACKETTYPE_SETSNOOPGUILD	(DWORD)0x00000022
#define	PACKETTYPE_SNOOP		(DWORD)0x00000023
//0x00000024	reserved
#define	PACKETTYPE_QUERY_DESTROY_PLAYER		(DWORD)0x00000030

#define	PACKETTYPE_NEW_ACCOUNT	(DWORD)0x000000f0
#define	PACKETTYPE_DEL_ACCOUNT	(DWORD)0x000000f1
#define	PACKETTYPE_CACHE_ADDR	(DWORD)0x000000f2
#define PACKETTYPE_PLAYER_LIST	(DWORD)0x000000f3
#define	PACKETTYPE_CREATE_PLAYER	(DWORD)0x000000f4
#define	PACKETTYPE_DEL_PLAYER	(DWORD)0x000000f5
#define	PACKETTYPE_GETPLAYERLIST	(DWORD)0x000000f6
#define	PACKETTYPE_SEL_PLAYER	(DWORD)0x000000f7
#define	PACKETTYPE_SAVE_PLAYER	(DWORD)0x000000f8
#define PACKETTYPE_GT	(DWORD)0x000000f9
#define	PACKETTYPE_ALLPLAYERID	(DWORD)0x000000fa
#define	PACKETTYPE_BUSY		(DWORD)0x000000fb
#define	PACKETTYPE_CERTIFY	(DWORD)0x000000fc
#define	PACKETTYPE_SRVR_LIST	(DWORD)0x000000fd
#define PACKETTYPE_ERROR	(DWORD)0x000000fe
#define	PACKETTYPE_PLAYERID	(DWORD)0x000000ff

//#define	PACKETTYPE_RETRY_CERT	(DWORD)0x00000ff0
#define	PACKETTYPE_ADD_OPERATORID	(DWORD)0x00000ff1
#define	PACKETTYPE_REMOVEPLAYERID	(DWORD)0x00000ff2
#define	PACKETTYPE_PLAYER_COUNT	(DWORD)0x00000ff3
#define	PACKETTYPE_ENABLE_SERVER	(DWORD)0x00000ff4
#define	PACKETTYPE_FAIL	(DWORD)0x00000ff5
#define	PACKETTYPE_NEWYEAR	(DWORD)0x00000ff6

/* patch
0x00000f00~0x00000fff
*/
//#define PACKETTYPE_CLIENT_FILE_LIST (DWORD)0x00000f00
#define PACKETTYPE_SEND_TO_CLIENT_NOTICE		(DWORD)0x00000f01
#define PACKETTYPE_SEND_TO_CLIENT_FILE_LIST		(DWORD)0x00000f02
#define PACKETTYPE_SEND_TO_SERVER_PATCH			(DWORD)0x00000f03
#define PACKETTYPE_SEND_TO_CLIENT_FILE			(DWORD)0x00000f04
#define PACKETTYPE_SEND_TO_CLIENT_PATCH			(DWORD)0x00000f05
#define PACKETTYPE_SEND_TO_CLIENT_PATCH_END		(DWORD)0x00000f06
#define PACKETTYPE_SEND_TO_CLIENT_PATCHCLIENTINFO (DWORD)0x00000f07
#define PACKETTYPE_SEND_TO_SERVER_PATCHCLIENT_CORRECT (DWORD)0x00000f08
#define PACKETTYPE_SEND_TO_SERVER_PATCHCLIENT_INCORRECT (DWORD)0x00000f09
#define PACKETTYPE_SEND_TO_CLIENT_PATCHCLIENT (DWORD)0x00000f0a
#define PACKETTYPE_SEND_TO_SERVER_REQUIRE_FILE (DWORD)0x00000f0b
#define PACKETTYPE_SEND_TO_SERVER_REQUIRE_FILE_LIST (DWORD)0x00000f0c
#define PACKETTYPE_SEND_TO_CLIENT_CDN			(DWORD)0x00000f0d

#define PACKETTYPE_SEND_TO_SERVER_EXP			(DWORD)0x00000f31  // seghope 서버에 경험치를 보냄(속성으로 렙업이 가능하게하는 패킷)
#define PACKETTYPE_SEND_TO_SERVER_CHANGEJOB		(DWORD)0x00000f32  // 전직( 속성으로 전직 번호를 줌 )
#define PACKETTYPE_SEND_TO_SERVER_AP			(DWORD)0x00000f33  // 액션 포인트 보냄.
#define PACKETTYPE_CHANGEJOB					(DWORD)0x00000f34  // 액션 포인트 보냄.
#define PACKETTYPE_ITEM_TBL_UPDATE				(DWORD)0x00000f35  // 아이템 업데이트

#define PACKETTYPE_JOIN		(DWORD)0x0000ff00
#define PACKETTYPE_LEAVE	(DWORD)0x0000ff01
#define	PACKETTYPE_DESTROY_ALLPLAYERS	(DWORD)0x0000ff02
#define	PACKETTYPE_REMOVE_ALLACCOUNTS	(DWORD)0x0000ff03
#define	PACKETTYPE_CLOSE_ERROR	(DWORD)0x0000ff04
#define	PACKETTYPE_PRE_JOIN	(DWORD)0x0000ff05

#define PACKETTYPE_GAMERATE				(DWORD)0x0000ff06
#define PACKETTYPE_SETMONSTERRESPAWN	(DWORD)0x0000ff07
#define PACKETTYPE_SETITEMEVENT			(DWORD)0x0000ff08


#define PACKETTYPE_CHAT			(DWORD)0x00ff0000
#define	PACKETTYPE_ACTMSG		(DWORD)0x00ff0001
#define	PACKETTYPE_ADDOBJ		(DWORD)0x00ff0002
#define	PACKETTYPE_REMOVEOBJ	(DWORD)0x00ff0003
#define PACKETTYPE_CONTROL		(DWORD)0x00ff0004

#define	PACKETTYPE_BROADCAST	(DWORD)0x000f0001
#define	PACKETTYPE_SAVEALLPLAYERS	(DWORD)0x000f0002
#define PACKETTYPE_DOUSESKILLPOINT	(DWORD)0x000f0003

#define PACKETTYPE_CREATEITEM	(DWORD)0x00ff0005
#define	PACKETTYPE_MOVEITEM		(DWORD)0x00ff0006
#define	PACKETTYPE_DROPITEM		(DWORD)0x00ff0007
#define	PACKETTYPE_DROPGOLD	(DWORD)0x00ff0008
#define PACKETTYPE_REMOVEITEM	(DWORD)0x00ff0009
#define	PACKETTYPE_SYNCITEM		(DWORD)0x00ff000a
#define	PACKETTYPE_DOEQUIP	(DWORD)0x00ff000b
#define	PACKETTYPE_DAMAGE	(DWORD)0x00ff000c
#define	PACKETTYPE_SETEXPERIENCE	(DWORD)0x00ff000d
#define	PACKETTYPE_REMOVEVENDORITEM	(DWORD)0x00ff000e
#define	PACKETTYPE_REMOVEALLITEM	(DWORD)0x00ff000f

#define	PACKETTYPE_MELEE_ATTACK		(DWORD)0x00ff0010
#define	PACKETTYPE_MAGIC_ATTACK		(DWORD)0x00ff0011
#define	PACKETTYPE_RANGE_ATTACK		(DWORD)0x00ff0012
#define	PACKETTYPE_MOVERDEATH		(DWORD)0x00ff0013
#define	PACKETTYPE_MELEE_ATTACK2	(DWORD)0x00ff0014

#define PACKETTYPE_SHIP_ACTMSG	(DWORD)0x00ff0015
#define	PACKETTYPE_MOTION	(DWORD)0x00ff0016
#define	PACKETTYPE_SETFXP	(DWORD)0x00ff0017

#define	PACKETTYPE_SETNAVIPOINT	(DWORD)0x00ff0018

#define	PACKETTYPE_USESKILL	(DWORD)0x00ff0020
#define PACKETTYPE_DOUSEITEM	(DWORD)0x00ff0021
#define PACKETTYPE_SFX_ID	(DWORD)0x00ff0022
#define	PACKETTYPE_SETTARGET	(DWORD)0x00ff0023
#define PACKETTYPE_SFX_CLEAR	(DWORD)0x00ff0024
#define PACKETTYPE_TELESKILL	(DWORD)0x00ff0025
#ifdef __V050322_CACHEQUEST
#define PACKETTYPE_REMOVEQUEST	(DWORD)0x00ff0026
#else //  __V050322_CACHEQUEST
//{{AFX
#define PACKETTYPE_QUESTCANCEL	(DWORD)0x00ff0026
//}}AFX
#endif //  __V050322_CACHEQUEST
#define PACKETTYPE_TRADECONFIRM		(DWORD)0x00ff002f
#define	PACKETTYPE_TRADE				(DWORD)0x00ff00a0
#define	PACKETTYPE_TRADEPUT				(DWORD)0x00ff00a1
#define	PACKETTYPE_TRADEPULL			(DWORD)0x00ff00a2
#define	PACKETTYPE_TRADEOK				(DWORD)0x00ff00a3
#define	PACKETTYPE_TRADECANCEL			(DWORD)0x00ff00a4
#define	PACKETTYPE_TRADEPUTGOLD			(DWORD)0x00ff00a5
#define	PACKETTYPE_TRADECLEARGOLD		(DWORD)0x00ff00a6
#define PACKETTYPE_CONFIRMTRADE			(DWORD)0x00ff00a7
#define PACKETTYPE_CONFIRMTRADECANCEL	(DWORD)0x00ff00a8

#define	PACKETTYPE_PVENDOR_OPEN	(DWORD)0x00ff00a9
#define	PACKETTYPE_PVENDOR_CLOSE		(DWORD)0x00ff00aa
#define	PACKETTYPE_REGISTER_PVENDOR_ITEM		(DWORD)0x00ff00ab
#define	PACKETTYPE_QUERY_PVENDOR_ITEM	(DWORD)0x00ff00ac
#define	PACKETTYPE_BUY_PVENDOR_ITEM		(DWORD)0x00ff00ad
#define	PACKETTYPE_UNREGISTER_PVENDOR_ITEM	(DWORD)0x00ff00ae
#define	PACKETTYPE_SET_HAIR		(DWORD)0x00ff00af

#define	PACKETTYPE_SCRIPTDLG	(DWORD)0x00ff00b0
#define	PACKETTYPE_OPENSHOPWND	(DWORD)0x00ff00b1
#define	PACKETTYPE_CLOSESHOPWND	(DWORD)0x00ff00b2
#define	PACKETTYPE_BUYITEM	(DWORD)0x00ff00b3
#define PACKETTYPE_SELLITEM		(DWORD)0x00ff00b4

#define	PACKETTYPE_REPAIRITEM	(DWORD)0x00ff00b5

#define	PACKETTYPE_REVIVAL						(DWORD)0x00ff00c0
#define	PACKETTYPE_REVIVAL_TO_LODESTAR			(DWORD)0x00ff00c1
#define	PACKETTYPE_REVIVAL_TO_LODELIGHT			(DWORD)0x00ff00c2
#define	PACKETTYPE_SETLODELIGHT					(DWORD)0x00ff00c3
#define	PACKETTYPE_INC_STAT_LEVEL				(DWORD)0x00ff00c4
#define	PACKETTYPE_INC_JOB_LEVEL				(DWORD)0x00ff00c5

#define	PACKETTYPE_ADDEXPERIENCE	(DWORD)0x00ff00d0
#define PACKETTYPE_SET_GROWTH_LEARNING_POINT	(DWORD)0x00ff00d1
#define	PACKETTYPE_SFX_HIT	(DWORD)0x00ff00d2
#define	PACKETTYPE_SETPOINTPARAM	(DWORD)0x00ff00d3
#define	PACKETTYPE_WHISPER	(DWORD)0x00ff00d4
#define	PACKETTYPE_ENDSKILLQUEUE				(DWORD)0x00ff00d5


#define	PACKETTYPE_CAPTION	(DWORD)0x00ff00d6

#define	PACKETTYPE_SAY	(DWORD)0x00ff00e0
#define	PACKETTYPE_SHOUT	(DWORD)0x00ff00e1
#define	PACKETTYPE_PLAYMUSIC	(DWORD)0x00ff00e2
#define	PACKETTYPE_PLAYSOUND	(DWORD)0x00ff00e3
#define	PACKETTYPE_SUMMONPLAYER		(DWORD)0x00ff00e4
#define	PACKETTYPE_TELEPORTPLAYER	(DWORD)0x00ff00e5
#define	PACKETTYPE_KILLPLAYER	(DWORD)0x00ff00e6
#define	PACKETTYPE_GETPLAYERADDR	(DWORD)0x00ff00e7
#define	PACKETTYPE_GETPLAYERCOUNT	(DWORD)0x00ff00e8
#define	PACKETTYPE_GETCOREPLAYER	(DWORD)0x00ff00e9
#define	PACKETTYPE_SYSTEM	(DWORD)0x00ff00ea
#define	PACKETTYPE_MODIFYMODE		(DWORD)0x00ff00eb
#define	PACKETTYPE_DEFINEDTEXT	(DWORD)0x00ff00ec
#define PACKETTYPE_GMSAY	(DWORD)0x00ff00ed               // 겜마에게 귓속말


#define PACKETTYPE_NW_RECOVERCHAO_MODE		(DWORD)0x00ff00ee	// 시련모드 설정을 요청
#define PACKETTYPE_NW_WANTED_GOLD			(DWORD)0x00ff00ef	// 현상금 걸기 패킷 
#define PACKETTYPE_NW_WANTED_LIST			(DWORD)0x00ff00f0   // 현상금 리스트 요청 패킷
#define PACKETTYPE_WN_WANTED_LIST			(DWORD)0x00ff00f1   // 현상금 리스트 응답 패킷
#define PACKETTYPE_NW_WANTED_INFO			(DWORD)0x00ff00f2   // 현상범 자세한정보 요청 패킷 
#define PACKETTYPE_WN_WANTED_INFO			(DWORD)0x00ff00f3   // 현상범 자세한정보 패킷 

#define PACKETTYPE_WC_WANTED_GOLD			(DWORD)0x00ff00f4	// 현상금을 설정 
#define PACKETTYPE_WC_WANTED_REWARD			(DWORD)0x00ff00f5	// 특정 플레이어의 현상금액 구하기 
#define PACKETTYPE_CW_WANTED_LIST			(DWORD)0x00ff00f6	// 현상금 리스트 보내기 
#define PACKETTYPE_CW_WANTED_REWARD			(DWORD)0x00ff00f7	// 현상금을 얻는다.

#define PACKETTYPE_CT_WANTED				(DWORD)0x00ff00f8	// 현상금을 처리요청 
#define PACKETTYPE_TC_LIST					(DWORD)0x00ff00f9	// 현상금 리스트 얻기 
#define PACKETTYPE_REQ_LEAVE				(DWORD)0x00ff00fa	// 접속 종료시도 패킷 
#define PACKETTYPE_WT_REQ_LEAVE				(DWORD)0x00ff00fb	// World->Trans 접속 종료시도 패킷 
#define PACKETTYPE_NW_WANTED_NAME			(DWORD)0x00ff00fc	// 현상범 이름 요청 
#define PACKETTYPE_WN_WANTED_NAME			(DWORD)0x00ff00fd	// 현상범 이름 응답 

#define PACKETTYPE_REPLACE					(DWORD)0x00ff0f00
#define	PACKETTYPE_CORR_REQ					(DWORD)0x00ff0ff0
#define	PACKETTYPE_SCRIPT_REMOVE_ALL_ITEM	(DWORD)0x00ff0ff1
#define	PACKETTYPE_SCRIPT_EQUIP_ITEM		(DWORD)0x00ff0ff2
#define	PACKETTYPE_SETQUEST					(DWORD)0x00ff0ff3
#define	PACKETTYPE_SCRIPT_CREATE_ITEM		(DWORD)0x00ff0ff4
#define	PACKETTYPE_SCRIPT_ADD_GOLD			(DWORD)0x00ff0ff5
#define	PACKETTYPE_SCRIPT_REMOVE_QUEST		(DWORD)0x00ff0ff6
#define	PACKETTYPE_SCRIPT_REPLACE			(DWORD)0x00ff0ff7
#define	PACKETTYPE_SCRIPT_REPLACE_KEY		(DWORD)0x00ff0ff8
#define	PACKETTYPE_SCRIPT_ADD_EXP      		(DWORD)0x00ff0ff9
#define	PACKETTYPE_SCRIPT_REMOVE_GOLD	(DWORD)0x00ff0ffa
#define	PACKETTYPE_SCRIPT_TRANS_PXP		(DWORD)0x00ff0ffb
#define	PACKETTYPE_SCRIPT_TRANS_PENYA	(DWORD)0x00ff0ffc
#define	PACKETTYPE_CREATE_GUILDCLOAK	(DWORD)0x00ff0ffd
#define PACKETTYPE_DO_COLLECT			(DWORD)0x00ff0ffe
#define PACKETTYPE_LOCALPOSFROMIA		(DWORD)0x00ff0fff

#define	PACKETTYPE_SNAPSHOT	(DWORD)0xffffff00
#define	PACKETTYPE_PLAYERMOVED	(DWORD)0xffffff01
#define	PACKETTYPE_PLAYERBEHAVIOR	(DWORD)0xffffff02
#define	PACKETTYPE_PLAYERMOVED2	(DWORD)0xffffff03
#define	PACKETTYPE_PLAYERBEHAVIOR2	(DWORD)0xffffff04
#define	PACKETTYPE_PLAYERCORR	(DWORD)0xffffff05
#define	PACKETTYPE_PLAYERCORR2	(DWORD)0xffffff06
#define	PACKETTYPE_PLAYERSETDESTOBJ	(DWORD)0xffffff07
#define	PACKETTYPE_QUERYGETPOS	(DWORD)0xffffff08
#define	PACKETTYPE_GETPOS	(DWORD)0xffffff09

#define	PACKETTYPE_REMOVEAPPLETTASKBAR	(DWORD)0xffffff0a
#define	PACKETTYPE_ADDAPPLETTASKBAR	(DWORD)0xffffff0b
#define	PACKETTYPE_ADDITEMTASKBAR	(DWORD)0xffffff0c
#define	PACKETTYPE_REMOVEITEMTASKBAR	(DWORD)0xffffff0d
#define	PACKETTYPE_SKILLTASKBAR	(DWORD)0xffffff0e

#define	PACKETTYPE_MOVERDESTPOS	(DWORD)0xffffff0f

#define PACKETTYPE_ERRORPARTY			(DWORD)0xffffff10
#define PACKETTYPE_ADDPARTYMEMBER		(DWORD)0xffffff11
#define PACKETTYPE_REMOVEPARTYMEMBER	(DWORD)0xffffff12
#define PACKETTYPE_ADDPLAYERPARTY		(DWORD)0xffffff13
#define PACKETTYPE_REMOVEPLAYERPARTY	(DWORD)0xffffff14
#define PACKETTYPE_MEMBERLEVEL			(DWORD)0xffffff15
#define PACKETTYPE_MEMBERJOB			(DWORD)0xffffff16
#define PACKETTYPE_MEMBERREQUEST		(DWORD)0xffffff17
#define PACKETTYPE_MEMBERREQUESTCANCLE  (DWORD)0xffffff18
#define PACKETTYPE_CHANGETROUP			(DWORD)0xffffff19
#define PACKETTYPE_CHANPARTYNAME		(DWORD)0xffffff1a
#define PACKETTYPE_PARTYSKILLUSE		(DWORD)0xffffff1b
#define PACKETTYPE_SETPARTYMODE			(DWORD)0xffffff1c
#define PACKETTYPE_ADDPARTYMEMBERSKILL	(DWORD)0xffffff1d
#define PACKETTYPE_ADDPARTYEXP			(DWORD)0xffffff1e
#define PACKETTYPE_REMOVEPARTYPOINT		(DWORD)0xffffff1f

#define PACKETTYPE_PARTYCHANGEITEMMODE	(DWORD)0xffffff20
#define PACKETTYPE_PARTYCHANGEEXPMODE	(DWORD)0xffffff21

#define	PACKETTYPE_SETPARTYEXP	(DWORD)0xffffff22

#define PACKETTYPE_DUELREQUEST		(DWORD)0xffffff23
#define PACKETTYPE_DUELYES			(DWORD)0xffffff24
#define PACKETTYPE_DUELNO			(DWORD)0xffffff25

#define PACKETTYPE_DUELPARTYREQUEST		(DWORD)0xffffff26
#define PACKETTYPE_DUELPARTYYES			(DWORD)0xffffff27
#define PACKETTYPE_DUELPARTYNO			(DWORD)0xffffff28
#define	PACKETTYPE_PLAYERANGLE			(DWORD)0xffffff29

#define	PACKETTYPE_SETPARTYDUEL		(DWORD)0xffffff2a

// 2b
#define PACKETTYPE_MOVERFOCOUS			(DWORD)0xffffff2d

#define	PACKETTYPE_PARTYCHANGELEADER	(DWORD)0xffffff2f

#define	PACKETTYPE_GUILD				(DWORD)0xffffff30
#define	PACKETTYPE_CREATE_GUILD			(DWORD)0xffffff31
#define	PACKETTYPE_DESTROY_GUILD		(DWORD)0xffffff32
#define	PACKETTYPE_ADD_GUILD_MEMBER		(DWORD)0xffffff33
#define	PACKETTYPE_REMOVE_GUILD_MEMBER	(DWORD)0xffffff34
#define	PACKETTYPE_GUILD_INVITE			(DWORD)0xffffff35
#define	PACKETTYPE_IGNORE_GUILD_INVITE	(DWORD)0xffffff36

#define	PACKETTYPE_QUERYPLAYERSTRING	(DWORD)0xffffff37
#define	PACKETTYPE_GLOBAL_DATA	(DWORD)0xffffff38

#define	PACKETTYPE_GUILD_CHAT			(DWORD)0xffffff39
#define	PACKETTYPE_GUILD_MEMBER_LEVEL	(DWORD)0xffffff3a
#define PACKETTYPE_GUILD_BANK_QUERY		(DWORD)0xffffff3b
#define PACKETTYPE_GUILD_BANK			(DWORD)0xffffff3c
#define PACKETTYPE_GUILD_BANK_UPDATE	(DWORD)0xffffff3d
#define PACKETTYPE_GUILD_BANK_WND_CLOSE	(DWORD)0xffffff3e
#define PACKETTYPE_GUILD_BANK_MOVEITEM	(DWORD)0xffffff3f


#define PACKETTYPE_OPENBANKWND		(DWORD)0xffffff40
#define PACKETTYPE_CLOSEBANKWND		(DWORD)0xffffff41
#define PACKETTYPE_PUTITEMBACK		(DWORD)0xffffff42
#define	PACKETTYPE_PUTGOLDBACK		(DWORD)0xffffff43
#define PACKETTYPE_GETITEMBACK		(DWORD)0xffffff44
#define	PACKETTYPE_GETGOLDBACK		(DWORD)0xffffff45
#define PACKETTYPE_MOVEBANKITEM		(DWORD)0xffffff46
#define PACKETTYPE_CHANGEBANKPASS	(DWORD)0xffffff47
#define PACKETTYPE_CONFIRMBANK		(DWORD)0xffffff48
#define PACKETTYPE_PUTBACKTOBANK	(DWORD)0xffffff49

#define PACKETTYPE_ENVIRONMENTSNOW	(DWORD)0xffffff50
#define PACKETTYPE_ENVIRONMENTRAIN	(DWORD)0xffffff51
#define PACKETTYPE_FALLRAIN			(DWORD)0xffffff52
#define PACKETTYPE_FALLSNOW			(DWORD)0xffffff53
#define PACKETTYPE_STOPRAIN			(DWORD)0xffffff54
#define PACKETTYPE_STOPSNOW			(DWORD)0xffffff55
#define PACKETTYPE_ENVIRONMENTALL	(DWORD)0xffffff56
#define PACKETTYPE_PARTYCHAT		(DWORD)0xffffff59
#define PACKETTYPE_BLOCK			(DWORD)0xffffff5a	// Friend Block
#define PACKETTYPE_SKILLFLAG		(DWORD)0xffffff5f	// 스킬 On / Off

#define PACKETTYPE_ADDFRIEND		(DWORD)0xffffff60
#define PACKETTYPE_ADDFRIENDREQEST  (DWORD)0xffffff61
#define PACKETTYPE_ADDFRIENDCANCEL  (DWORD)0xffffff62
#define PACKETTYPE_GETFRIENDNAME	(DWORD)0xffffff63
#define PACKETTYPE_GETFRIENDSTATE	(DWORD)0xffffff64
#define PACKETTYPE_ADDFRIENDJOIN	(DWORD)0xffffff65
#define PACKETTYPE_ADDFRIENDLOGOUT	(DWORD)0xffffff66
#define PACKETTYPE_SETFRIENDSTATE	(DWORD)0xffffff67
#define PACKETTYPE_FRIENDINTERCEPTSTATE		(DWORD)0xffffff68
#define PACKETTYPE_FRIENDNOINTERCEPT		(DWORD)0xffffff69
#define PACKETTYPE_REMOVEFRIEND		(DWORD)0xffffff6a
#define PACKETTYPE_ADDFRIENDNAMEREQEST		(DWORD)0xffffff6b
#define PACKETTYPE_ADDFRIENDNAMENOTFOUND	(DWORD)0xffffff6c
#define PACKETTYPE_REMOVEFRIENDSTATE		(DWORD)0xffffff6d
#define PACKETTYPE_ONEFRIEMDSTATE			(DWORD)0xffffff6e

#define PACKETTYPE_PARTYNAME			(DWORD)0xffffff70
#define PACKETTYPE_ADDPARTYNAME		(DWORD)0xffffff71

#define	PACKETTYPE_QUERYGETDESTOBJ	(DWORD)0xffffff72
#define	PACKETTYPE_GETDESTOBJ	(DWORD)0xffffff73

#define	PACKETTYPE_GUILD_CLASS			(DWORD)0xffffff74
#define	PACKETTYPE_GUILD_NICKNAME		(DWORD)0xffffff75
#define PACKETTYPE_GUILD_MEMBERTIME		(DWORD)0xffffff76
#define PACKETTYPE_GUILD_MEMBERLOGOUT	(DWORD)0xffffff77
#define PACKETTYPE_RESURRECTION_OK	(DWORD)0xffffff78
#define PACKETTYPE_RESURRECTION_CANCEL	(DWORD)0xffffff79

#define PACKETTYPE_STATEMODE		(DWORD)0xffffff7a
#define PACKETTYPE_MODE				(DWORD)0xffffff7b

#define	PACKETTYPE_CHEERING		(DWORD)0xffffff7c

#define PACKETTYPE_SAVE_CONCURRENT_USER_NUMBER (DWORD)0x0f000f00
#define PACKETTYPE_SAVE_CONCURRENT_FIELD_USER_NUMBER (DWORD)0x0f000f01
#define	PACKETTYPE_LOG_PLAY_CONNECT	(DWORD)0x0f000f02
#define PACKETTYPE_LOG_PLAY_DEATH	(DWORD)0x0f000f03
#define PACKETTYPE_LOG_LEVELUP		(DWORD)0x0f000f04
#define PACKETTYPE_LOG_SERVER_DEATH	(DWORD)0x0f000f05
#define PACKETTYPE_LOG_UNIQUEITEM	(DWORD)0x0f000f06
#define PACKETTYPE_LOG_ALLITEM		(DWORD)0x0f000f07
#define PACKETTYPE_LOG_QUEST		(DWORD)0x0f000f08
#define PACKETTYPE_LOG_GAMEMASTER_CHAT	(DWORD)0x0f000f09
#define PACKETTYPE_LOG_PK_PVP		(DWORD)0x0f000f0a
#define PACKETTYPE_LOG_SCHOOL		(DWORD)0x0f000f0b
#define PACKETTYPE_PREVENT_LOGIN	(DWORD)0x0f000f0c

#define	PACKETTYPE_FREQUENCY_LOG	(DWORD)0x0f000f0f

#define	PACKETTYPE_MONITOR_ID	(DWORD)0xf0008000
#define	PACKETTYPE_CONSOLE_COMMAND	(DWORD)0xf0008001
#define	PACKETTYPE_CONSOLE_OVERVIEW	(DWORD)0xf0008002
#define	PACKETTYPE_CONSOLE_FILEHEADER (DWORD)0xf0008003
#define	PACKETTYPE_CONSOLE_FILEDATA   (DWORD)0xf0008004
#define PACKETTYPE_CONSOLE_UPLOADACK  (DWORD)0xf0008005
#define PACKETTYPE_CONSOLE_EXPAND	(DWORD)0xf0008006
#define PACKETTYPE_CONSOLE_SYNCACK	(DWORD)0xf0008007
#define PACKETTYPE_CONSOLE_EXPANDACK (DWORD)0xf0008008
#define	PACKETTYPE_CONSOLE_OVERVIEW2	(DWORD)0xf0008009

#define	PACKETTYPE_PROCESS_CREATED	(DWORD)0xf0009000
#define	PACKETTYPE_PROCESS_TERMINATED	(DWORD)0xf0009001
#define	PACKETTYPE_MY_PROCESS	(DWORD)0xf0009002
#define	PACKETTYPE_CREATE_PROCESS	(DWORD)0xf000a000
#define	PACKETTYPE_TERMINATE_PROCESS	(DWORD)0xf000a001
#define	PACKETTYPE_TERMINATE_PROCESS_AND_QUIT	(DWORD)0xf000a002
#define	PACKETTYPE_PROCESS_MODE		(DWORD)0xf000a003
#define	PACKETTYPE_ADD_ACCOUNT		(DWORD)0xf000b000
#define	PACKETTYPE_REMOVE_ACCOUNT	(DWORD)0xf000b001
#define	PACKETTYPE_ROUTE			(DWORD)0xf000b002
#define	PACKETTYPE_DESTROY_PLAYER	(DWORD)0xf000b003
#define PACKETTYPE_ERRORCODE		(DWORD)0xf000b004
#define PACKETTYPE_PROCESS_CREATED2		(DWORD)0xf000b005 
#define	PACKETTYPE_PROCESS_TERMINATED2	(DWORD)0xf000b006
#define	PACKETTYPE_MY_PROCESS2			(DWORD)0xf0009007
#define PACKETTYPE_RENEWEVNET		(DWORD)0xf000b005

// TAG관련 
#define PACKETTYPE_TAG				(DWORD)0xf000b006
#define PACKETTYPE_SENDTAG			(DWORD)0xf000b007
#define PACKETTYPE_INSERTTAG_RESULT	(DWORD)0xf000b008

#define PACKETTYPE_PARTYLEVEL		(DWORD)0xf000b009

#define PACKETTYPE_WC_GUILDLOGO		(DWORD)0xf000b00a	// 로고변경 
#define PACKETTYPE_WC_GUILDCONTRIBUTION    (DWORD)0xf000b00b	// 공헌 (페냐와 PXP공헌 횟수)
#define PACKETTYPE_WC_GUILDNOTICE   (DWORD)0xf000b00c	// 공지사항 변경 
#define PACKETTYPE_CW_GUILDLOGO		(DWORD)0xf000b00d	// 로고변경 
#define PACKETTYPE_CW_GUILDCONTRIBUTION	(DWORD)0xf000b00e	// 공헌 
#define PACKETTYPE_CW_GUILDNOTICE   (DWORD)0xf000b00f	// 공지사항 변경 

#define	PACKETTYPE_NW_GUILDLOGO			(DWORD)0xf000b010	// 로고 변경 
#define	PACKETTYPE_NW_GUILDCONTRIBUTION	(DWORD)0xf000b011	// 공헌도 
#define	PACKETTYPE_NW_GUILDNOTICE		(DWORD)0xf000b012	// 공지사항 
#define	PACKETTYPE_FOCUSOBJ				(DWORD)0xf000b013	

// World에서 Neuz로는 snapshop으로 

#define PACKETTYPE_CD_GUILD_LOGO			(DWORD)0xf000b016	// 로고 
#define PACKETTYPE_WD_GUILD_CONTRIBUTION	(DWORD)0xf000b017	// 공헌 
#define PACKETTYPE_CD_GUILD_NOTICE			(DWORD)0xf000b018	// 공지 

#define PACKETTYPE_GUILD_BANK_WND			(DWORD)0xf000b020	// 길드 창고 오픈 
#define PACKETTYPE_PUTITEMGUILDBANK			(DWORD)0xf000b021	// 길드 창고 아이템 넣기(풋~~ ^^;;; )
#define PACKETTYPE_GETITEMGUILDBANK			(DWORD)0xf000b022	
#define PACKETTYPE_GUILD_MSG_CONTROL		(DWORD)0xf000b023	

#define PACKETTYPE_GUILD_AUTHORITY			(DWORD)0xf000b026	// 길드 권한 설정( Authority가 권한이라니~ 꾹~~ ㅋㄷㅋㄷ )
#define PACKETTYPE_GUILD_PENYA				(DWORD)0xf000b027	// 길드 PENYA 설정
#define PACKETTYPE_GUILD_DB_REALPENYA		(DWORD)0xf000b028	// 길드 PENYA 실제로 길드원들에 주기
#define PACKETTYPE_GUILD_GAMELOGIN			(DWORD)0xf000b029	// 길드원이 게임에 들어옴
#define PACKETTYPE_GUILD_GAMEJOIN			(DWORD)0xf000b030	// 게임에 들어왔으므로 나에게 길드원 정보를 줌
#define PACKETTYPE_CHANGEGUILDJOBLEVEL		(DWORD)0xf000b031	// 전직했을때/레벨업했을시 길드원들에게 알려줌
#define PACKETTYPE_GUILD_SETNAME			(DWORD)0xf000b032	// 길드이름을 바꿈

#define PACKETTYPE_GUILD_ERROR				(DWORD)0xf000b035	// 길드 에러 정보 보내기
#define	PACKETTYPE_DECL_GUILD_WAR			(DWORD)0xf000b036	// 길드 전쟁 선포
#define	PACKETTYPE_ACPT_GUILD_WAR			(DWORD)0xf000b037	// 길드 전쟁 시작
#define PACKETTYPE_NC_ADDVOTE				(DWORD)0xf000b038	// 투표 입력 
#define PACKETTYPE_NC_REMOVEVOTE			(DWORD)0xf000b039	// 투표 취소 
#define PACKETTYPE_NC_CLOSEVOTE				(DWORD)0xf000b03a	// 투표 종료 
#define PACKETTYPE_NC_CASTVOTE				(DWORD)0xf000b03b	// 투표하기 

#define PACKETTYPE_CD_ADDVOTE				(DWORD)0xf000b03c   // 투표 입력(CORE -> DB)
#define PACKETTYPE_CD_REMOVEVOTE			(DWORD)0xf000b03d	// 투표 취소(CORE -> DB)
#define PACKETTYPE_CD_CLOSEVOTE				(DWORD)0xf000b03e	// 투표 종료(CORE -> DB)
#define PACKETTYPE_CD_CASTVOTE				(DWORD)0xf000b03f	// 투표하기 (CORE -> DB)
#define PACKETTYPE_DC_ADDVOTERESULT			(DWORD)0xf000b040	// 투표 입력결과 (DB -> CORE)
#define PACKETTYPE_CW_ADDVOTERESULT			(DWORD)0xf000b041	// 투표 입력결과 (CORE -> WORLD)
#define PACKETTYPE_CW_MODIFYVOTE			(DWORD)0xf000b042	// 투표 변경  (CORE -> WORLD)

#define PACKETTYPE_UPDATE_GUILD_RANKING		(DWORD)0xf000b043	// 길드랭킹을 업데이트하기
#define PACKETTYPE_UPDATE_GUILD_RANKING_END	(DWORD)0xf000b044	// 길드랭킹을 업데이트 완료		
#define PACKETTYPE_UPDATE_GUILD_RANKING_DB	(DWORD)0xf000b04d	// 길드랭킹을 업데이트하기
#define PACKETTYPE_REQUEST_GUILD_RANKING	(DWORD)0xf000b04e	// 길드랭킹을 요청하기

#define	PACKETTYPE_WAR_DEAD		(DWORD)0Xf000b045	// 길드전 사망
#define	PACKETTYPE_WAR_END	(DWORD)0xf000b046	// 종전
#define	PACKETTYPE_SURRENDER	(DWORD)0xf000b047	// 항복
#define	PACKETTYPE_QUERY_TRUCE	(DWORD)0xf000b048	// 정전 요청
#define	PACKETTYPE_ACPT_TRUCE	(DWORD)0xf000b049	// 정전 수락
#define	PACKETTYPE_WAR_TIMEOUT	(DWORD)0xf000b04a	// 전시 종료
#define	PACKETTYPE_WAR_MASTER_ABSENT	(DWORD)0xf000b04b	// 길드 마스터 부재
#define	PACKETTYPE_SCHOOL_REPORT	(DWORD)0xf000b04c
#define PACKETTYPE_COMMERCIALELEM	(DWORD)0xf000b04f
#define	PACKETTYPE_UPGRADEBASE		(DWORD)0xf000b050
#define	PACKETTYPE_ENCHANT			(DWORD)0xf000b024
#define	PACKETTYPE_PIERCING			(DWORD)0xf000b025
#define	PACKETTYPE_PIERCING_SIZE	(DWORD)0xf000d008
#define	PACKETTYPE_QUERYEQUIP		(DWORD)0xf000d009
#define	PACKETTYPE_QUERYEQUIPSETTING	(DWORD)0xf000d00a
#define PACKETTYPE_PIERCING_REMOVE	(DWORD)0xf000d00b

#define	PACKETTYPE_UPDATEGUILDQUEST	(DWORD)0xf000b051
#define	PACKETTYPE_BUYING_INFO	(DWORD)0xf000b052
#define	PACKETTYPE_QUERYGUILDQUEST	(DWORD)0xf000b053

#define PACKETTYPE_ENTERCHTTING		(DWORD)0xf000b054
#define PACKETTYPE_CHATTING			(DWORD)0xf000b055

#define	PACKETTYPE_INSERTGUILDQUEST		(DWORD)0xf000b056

#define PACKETTYPE_COMMONPLACE			(DWORD)0xf000b057

#define PACKETTYPE_OPENCHATTINGROOM		(DWORD)0xf000b058
#define PACKETTYPE_CLOSECHATTINGROOM	(DWORD)0xf000b059

#define	PACKETTYPE_DELETEGUILDQUEST		(DWORD)0xf000b05a

#define	PACKETTYPE_OPEN_BATTLESERVER	(DWORD)0xf000d000
#define	PACKETTYPE_CLOSE_BATTLESERVER	(DWORD)0xf000d001
#define	PACKETTYPE_JOIN_BATTLESERVER	(DWORD)0xf000d002
#define	PACKETTYPE_BASEGAMESETTING		(DWORD)0xf000d003
#define PACKETTYPE_MONSTERRESPAWNSETTING		(DWORD)0xf000d004
#define PACKETTYPE_MONSTERPROPGAMESETTING		(DWORD)0xf000d005
#define PACKETTYPE_GAMEMASTER_CHATTING			(DWORD)0xf000d006

#define PACKETTYPE_RELOAD_PROJECT				(DWORD)0xf000d007
#define PACKETTYPE_CREATESFXOBJ					(DWORD)0xf000d00f
#define	PACKETTYPE_RETURNSCROLL					(DWORD)0xf000d010
	
#define	PACKETTYPE_EVENT0913						(DWORD)0xf000d011

#ifdef __GUILDCOMBAT
#define	PACKETTYPE_ADD_GUILDCOMBAT	(DWORD)0xf000d012
#define	PACKETTYPE_IN_GUILDCOMBAT		(DWORD)0xf000d013
#define	PACKETTYPE_OUT_GUILDCOMBAT	(DWORD)0xf000d014
#define	PACKETTYPE_JOIN_GUILDCOMBAT	(DWORD)0xf000d015
#define	PACKETTYPE_STATE_GUILDCOMBAT	(DWORD)0xf000d016
#define	PACKETTYPE_RESULT_GUILDCOMBAT	(DWORD)0xf000d017
#define PACKETTYPE_GUILDCOMBAT_STATE	(DWORD)0xf000d018
#define PACKETTYPE_GUILDCOMBAT_RANKING	(DWORD)0xf000d019
#endif // __GUILDCOMBAT

#define	PACKETTYPE_EVENT1206						(DWORD)0xf000d01a
#define	PACKETTYPE_EVENT							(DWORD)0xf000d01b

#define	PACKETTYPE_CHG_MASTER	(DWORD)0xf000f000



/*------------------------------------------------------------------------------------------------------------------------------------------------------------*/

#define SNAPSHOTTYPE_CHAT	(BYTE)0x01
#define SNAPSHOTTYPE_ACTMSG	(BYTE)0x02
#define SNAPSHOTTYPE_CREATEITEM	(BYTE)0x03
#define	SNAPSHOTTYPE_MOVEITEM	(BYTE)0x04

#define	SNAPSHOTTYPE_TRADEPUTERROR (BYTE)0x05
#define	SNAPSHOTTYPE_DOEQUIP	(BYTE)0x06
#define	SNAPSHOTTYPE_TRADE	(BYTE)0x07
#define	SNAPSHOTTYPE_TRADEPUT	(BYTE)0x08
#define	SNAPSHOTTYPE_TRADEPULL	(BYTE)0x09
#define	SNAPSHOTTYPE_TRADEOK	(BYTE)0x0a
#define	SNAPSHOTTYPE_TRADECANCEL	(BYTE)0x0b
#define	SNAPSHOTTYPE_TRADECONSENT	(BYTE)0x0c
#define SNAPSHOTTYPE_SYNCITEM	(BYTE)0x0d
#define SNAPSHOTTYPE_SETPOSANGLE	(BYTE)0x0e
#define	SNAPSHOTTYPE_CREATESFXOBJ	(BYTE)0x0f

#define SNAPSHOTTYPE_SETPOS	(BYTE)0x10
#define SNAPSHOTTYPE_SETLEVEL	(BYTE)0x11
#define	SNAPSHOTTYPE_SETEXPERIENCE	(BYTE)0x12
#define	SNAPSHOTTYPE_DAMAGE	(BYTE)0x13
#define	SNAPSHOTTYPE_OPENSHOPWND	(BYTE)0x14
#define	SNAPSHOTTYPE_VENDOR	(BYTE)0x15
#define	SNAPSHOTTYPE_UPDATE_VENDOR	(BYTE)0x16
#define	SNAPSHOTTYPE_UPDATE_MOVER	(BYTE)0x17
#define	SNAPSHOTTYPE_UPDATE_ITEM	(BYTE)0x18
#define	SNAPSHOTTYPE_USESKILL	(BYTE)0x19
#define SNAPSHOTTYPE_CLEAR_USESKILL	(BYTE)0x1a
#define	SNAPSHOTTYPE_QUERYGETPOS		(BYTE)0x1b

#define	SNAPSHOTTYPE_SETDESTPARAM	(BYTE)0x1c
#define	SNAPSHOTTYPE_RESETDESTPARAM	(BYTE)0x1d
#define	SNAPSHOTTYPE_SETPOINTPARAM	(BYTE)0x1e

#define	SNAPSHOTTYPE_GETPOS		(BYTE)0x1f

#define	SNAPSHOTTYPE_TRADEPUTGOLD	(BYTE)0x20
#define	SNAPSHOTTYPE_TRADECLEARGOLD	(BYTE)0x21
#define	SNAPSHOTTYPE_CONFIRMTRADE	(BYTE)0x22
#define	SNAPSHOTTYPE_CONFIRMTRADECANCEL	(BYTE)0x23

#define	SNAPSHOTTYPE_RUNSCRIPTFUNC	(BYTE)0x24

#define	SNAPSHOTTYPE_SETSKILLEXP	(BYTE)0x25
#define	SNAPSHOTTYPE_SETSKILLLEVEL	(BYTE)0x26
#define	SNAPSHOTTYPE_RESURRECTION_MESSAGE	(BYTE)0x27
#define	SNAPSHOTTYPE_SET_SLAUGHTER_POINT	(BYTE)0x28
#define	SNAPSHOTTYPE_SETFXP			(BYTE)0x29
#define SNAPSHOTTYPE_SETFLIGHTLEVEL	(BYTE)0x2a

#define	SNAPSHOTTYPE_TRADELASTCONFIRM	(BYTE)0x2b
#define	SNAPSHOTTYPE_TRADELASTCONFIRMOK	(BYTE)0x2c

#ifdef __SCHOOL0701
#define	SNAPSHOTTYPE_SCHOOL_REPORT	(BYTE)0x2d
#endif	// __SCHOOL0701

#define SNAPSHOTTYPE_GAMERATE		(BYTE)0x2e
#define SNAPSHOTTYPE_EVENTMESSAGE	(BYTE)0x2f

#define SNAPSHOTTYPE_DUELREQUEST (BYTE)0x30
#define SNAPSHOTTYPE_DUELSTART	 (BYTE)0x31
#define SNAPSHOTTYPE_DUELNO		 (BYTE)0x32
#define SNAPSHOTTYPE_DUELCANCEL	 (BYTE)0x33
#define SNAPSHOTTYPE_DUELPARTYREQUEST (BYTE)0x34
#define SNAPSHOTTYPE_DUELPARTYSTART	 (BYTE)0x35
#define SNAPSHOTTYPE_DUELPARTYNO		 (BYTE)0x36
#define SNAPSHOTTYPE_DUELPARTYCANCEL	 (BYTE)0x37
#define SNAPSHOTTYPE_DUELPARTYRESULT	 (BYTE)0x38
#define SNAPSHOTTYPE_SETSCALE			(BYTE)0x39
#ifdef __V050322_CACHEQUEST
#define SNAPSHOTTYPE_REMOVEQUEST		(BYTE)0x3a
#else // __V050322_CACHEQUEST
//{{AFX
#define SNAPSHOTTYPE_QUESTCANCEL		(BYTE)0x3a
//}}AFX
#endif // __V050322_CACHEQUEST
#define SNAPSHOTTYPE_MOVERFOCUS		(BYTE)0x3b
#define SNAPSHOTTYPE_PARTYMAPINFO	(BYTE)0x3c

#define SNAPSHOTTYPE_SM_MODE_ALL	(BYTE)0x3e
#define	SNAPSHOTTYPE_SM_MODE		(BYTE)0x3f

#define SNAPSHOTTYPE_SETFAME	(BYTE)0x40
#define SNAPSHOTTYPE_CORRREQ	(BYTE)0x41

#define	SNAPSHOTTYPE_PVENDOR_OPEN	(BYTE)0x42
#define	SNAPSHOTTYPE_PVENDOR_CLOSE	(BYTE)0x43
#define	SNAPSHOTTYPE_REGISTER_PVENDOR_ITEM	(BYTE)0x44
#define	SNAPSHOTTYPE_PVENDOR_ITEM	(BYTE)0x45
#define	SNAPSHOTTYPE_PVENDOR_ITEM_NUM	(BYTE)0x46
#define	SNAPSHOTTYPE_UNREGISTER_PVENDOR_ITEM	(BYTE)0x47
#define	SNAPSHOTTYPE_SET_HAIR	(BYTE)0x48

#define	SNAPSHOTTYPE_QUERYGETDESTOBJ	(BYTE)0x49
#define	SNAPSHOTTYPE_GETDESTOBJ		(BYTE)0x4a
#define SNAPSHOTTYPE_SETFUEL		(BYTE)0x4b
#define SNAPSHOTTYPE_SETSKILLSTATE	(BYTE)0x4c

#define SNAPSHOTTYPE_CHANGEFACE		(BYTE)0x4d

#define SNAPSHOTTYPE_MONSTERPROP	(BYTE)0x4e
#define SNAPSHOTTYPE_GMCHAT			(BYTE)0x4f

#define SNAPSHOTTYPE_PUTITEMBANK		(BYTE)0x50
#define SNAPSHOTTYPE_GETITEMBANK		(BYTE)0x51
#define SNAPSHOTTYPE_PUTGOLDBANK		(BYTE)0x52
#define SNAPSHOTTYPE_MOVEBANKITEM		(BYTE)0x53
#define SNAPSHOTTYPE_UPDATE_BANKITEM	(BYTE)0x54
#define	SNAPSHOTTYPE_BANKISFULL			(BYTE)0x55
#define SNAPSHOTTYPE_BANKWINDOW			(BYTE)0x56
#define SNAPSHOTTYPE_CHANGEBANKPASS		(BYTE)0x57
#define SNAPSHOTTYPE_CONFIRMBANKPASS	(BYTE)0x58
#define SNAPSHOTTYPE_SETSTUN			(BYTE)0x59
#define SNAPSHOTTYPE_SETPOISON			(BYTE)0x5a
#define SNAPSHOTTYPE_SETDARK			(BYTE)0x5b
#define SNAPSHOTTYPE_SENDACTMSG			(BYTE)0x5c

#define SNAPSHOTTYPE_RESISTSMMODE		(BYTE)0x5d
#define SNAPSHOTTYPE_COMMERCIALELEM		(BYTE)0x5e
#define SNAPSHOTTYPE_PUSHPOWER			(BYTE)0x5f
#define SNAPSHOTTYPE_ENVIRONMENT		(BYTE)0x60
#define SNAPSHOTTYPE_ENVIRONMENTSNOW	(BYTE)0x61
#define SNAPSHOTTYPE_ENVIRONMENTRAIN	(BYTE)0x62
#define SNAPSHOTTYPE_ENVIRONMENTALL		(BYTE)0x63
#define SNAPSHOTTYPE_SKILLFLAG			(BYTE)0x64
#define SNAPSHOTTYPE_UPDATE_PLAYER_ENEMY	(BYTE)0x65
#define SNAPSHOTTYPE_SETDUEL			(BYTE)0x66
#define SNAPSHOTTYPE_DUELCOUNT			(BYTE)0x67
#define SNAPSHOTTYPE_ADDPARTYNAME		(BYTE)0x68
#define SNAPSHOTTYPE_PARTYCHAT			(BYTE)0x69
#define SNAPSHOTTYPE_SETSTATE			(BYTE)0x6a
#define SNAPSHOTTYPE_CMDSETSKILLLEVEL	(BYTE)0x6b
#define SNAPSHOTTYPE_DO_COLLECT			(BYTE)0x6c
#define SNAPSHOTTYPE_STOP_COLLECT		(BYTE)0x6d
#define SNAPSHOTTYPE_ACTIVESKILL		(BYTE)0x6e
#define SNAPSHOTTYPE_RESETBUFFSKILL		(BYTE)0x6f
#define SNAPSHOTTYPE_ADDFRIEND			(BYTE)0x70
#define SNAPSHOTTYPE_ADDFRIENDREQEST    (BYTE)0x71
#define SNAPSHOTTYPE_ADDFRIENDCANCEL	(BYTE)0x72
#define SNAPSHOTTYPE_ADDGETFRIENDNAME	(BYTE)0x73
#define SNAPSHOTTYPE_ADDFRIENDGAMEJOIN	(BYTE)0x74
#define SNAPSHOTTYPE_REMOVEFRIEND		(BYTE)0x75
#define SNAPSHOTTYPE_ADDFRIENDERROR		(BYTE)0x76
#define SNAPSHOTTYPE_ADDFRIENDCHANGEJOB	(BYTE)0x77
#define SNAPSHOTTYPE_ADDGAMEJOIN		(BYTE)0x78
#define SNAPSHOTTYPE_ADDPARTYCHANGELEADER	(BYTE)0x79

#define	SNAPSHOTTYPE_SET_WAR	(BYTE)0x7a
#define SNAPSHOTTYPE_CHATTING	(BYTE)0x7b
#define SNAPSHOTTYPE_INITSKILLPOINT		(BYTE)0x7c
#define SNAPSHOTTYPE_DOUSESKILLPOINT	(BYTE)0x7d
#define SNAPSHOTTYPE_COMMONPlACE		(BYTE)0x7e
#define SNAPSHOTTYPE_END_RECOVERMODE	(BYTE)0x7f
#define SNAPSHOTTYPE_WANTED_INFO		(BYTE)0x80

#define SNAPSHOTTYPE_ERRORPARTY			(BYTE)0x81
#define SNAPSHOTTYPE_PARTYMEMBER		(BYTE)0x82
#define SNAPSHOTTYPE_PARTYREQEST		(BYTE)0x83
#define SNAPSHOTTYPE_PARTYREQESTCANCEL	(BYTE)0x84
#define SNAPSHOTTYPE_PARTYEXP			(BYTE)0x85
#define SNAPSHOTTYPE_PARTYMEMBERJOB		(BYTE)0x86
#define SNAPSHOTTYPE_PARTYMEMBERLEVEL	(BYTE)0x87
#define SNAPSHOTTYPE_PARTYCHANGETROUP	(BYTE)0x88
#define SNAPSHOTTYPE_PARTYCHANGENAME	(BYTE)0x89
#define SNAPSHOTTYPE_PARTYSKILL_CALL	(BYTE)0x8a
#define SNAPSHOTTYPE_PARTYSKILL_BLITZ	(BYTE)0x8b
#define SNAPSHOTTYPE_PARTYSKILL_RETREAT	(BYTE)0x8c
#define SNAPSHOTTYPE_SETPARTYMODE				(BYTE)0x8d
#define SNAPSHOTTYPE_PARTYSKILL_SPHERECIRCLE	(BYTE)0x8e
#define SNAPSHOTTYPE_PARTYCHANGEITEMMODE	(BYTE)0x8f
#define SNAPSHOTTYPE_PARTYCHANGEEXPMODE	(BYTE)0x90
#define	SNAPSHOTTYPE_SET_PARTY_MEMBER_PARAM	(BYTE)0x91
#define SNAPSHOTTYPE_DO_ESCAPE				(BYTE)0x92
#define	SNAPSHOTTYPE_SNOOP	(BYTE)0x93
#define	SNAPSHOTTYPE_DEFINEDTEXT1	(BYTE)0x94
#define	SNAPSHOTTYPE_DEFINEDTEXT	(BYTE)0x95
#define SNAPSHOTTYPE_GAMETIMER	(BYTE)0x96
#define SNAPSHOTTYPE_TASKBAR	(BYTE)0x97
#define	SNAPSHOTTYPE_MOTION		(BYTE)0x98
#define	SNAPSHOTTYPE_QUERYPLAYERSTRING	(BYTE)0x99
#define	SNAPSHOTTYPE_GUILD_INVITE	(BYTE)0x9a
#define	SNAPSHOTTYPE_SET_GUILD		(BYTE)0x9b
#define	SNAPSHOTTYPE_CREATE_GUILD	(BYTE)0x9c
#define	SNAPSHOTTYPE_DESTROY_GUILD	(BYTE)0x9d
#define	SNAPSHOTTYPE_GUILD			(BYTE)0x9e
#define	SNAPSHOTTYPE_ALL_GUILDS		(BYTE)0x9f

#define SNAPSHOTTYPE_TEXT	(BYTE)0xa0
#define SNAPSHOTTYPE_REVIVAL	(BYTE)0xa1
#define SNAPSHOTTYPE_REVIVAL_TO_LODESTAR	(BYTE)0xa2
#define SNAPSHOTTYPE_REVIVAL_TO_LODELIGHT	(BYTE)0xa3
#define	SNAPSHOTTYPE_SET_STAT_LEVEL		(BYTE)0xa4
#define	SNAPSHOTTYPE_SET_JOB_LEVEL	(BYTE)0xa5
#define	SNAPSHOTTYPE_SET_GROWTH_LEARNING_POINT	(BYTE)0xa6

#define SNAPSHOTTYPE_SET_JOB_SKILL		(BYTE)0xa7
#define SNAPSHOTTYPE_SET_NEAR_JOB_SKILL (BYTE)0xa8
#define SNAPSHOTTYPE_RETURNSAY			(BYTE)0xa9				// 귓속말에서 되돌아오는것 : 찾을수가 없음, 귓속말 내용
#define SNAPSHOTTYPE_CREATESFXALLOW		(BYTE)0xaa
#define	SNAPSHOTTYPE_REMOVEITEMATID		(BYTE)0xab
#define	SNAPSHOTTYPE_QUERYEQUIP			(BYTE)0xac
#define SNAPSHOTTYPE_RETURNSCORLL		(BYTE)0xad
#define SNAPSHOTTYPE_SETTARGET			(BYTE)0xae
#define SNAPSHOTTYPE_FOCUSOBJ			(BYTE)0xaf

#define SNAPSHOTTYPE_SETQUEST	(BYTE)0xb0
#ifndef __V050322_CACHEQUEST
//{{AFX
#define	SNAPSHOTTYPE_SCRIPT_REMOVEQUEST	(BYTE)0xb1
//}}AFX
#endif // __V050322_CACHEQUEST
#define	SNAPSHOTTYPE_FLYFF_EVENT	(BYTE)0xb2
#define	SNAPSHOTTYPE_SET_LOCAL_EVENT	(BYTE)0xb3

#define	SNAPSHOTTYPE_SETCHEERPARAM	(BYTE)0xb4

#define SNAPSHOTTYPE_SETGUILDQUEST		(BYTE)0xb5
#define SNAPSHOTTYPE_REMOVEGUILDQUEST	(BYTE)0xb6
#define SNAPSHOTTYPE_DIAG_TEXT				(BYTE)0xb7
#define SNAPSHOTTYPE_GUILDCOMBATRANKING			(BYTE)0xb8
#define	SNAPSHOTTYPE_GUILDCOMBATWINGUILD		(BYTE)0xb9
#define	SNAPSHOTTYPE_GUILDCOMBATWARLISTING		(BYTE)0xba
#define SNAPSHOTTYPE_GUILDCOMBATENTERTIME		(BYTE)0xbb
#define SNAPSHOTTYPE_GUILDCOMBATNEXTTIMESTATE	(BYTE)0xbc
#define	SNAPSHOTTYPE_GUILDCOMBATSTATE			(BYTE)0xbd
#define SNAPSHOTTYPE_GUILDCOMBATLIST			(BYTE)0xbe
#define SNAPSHOTTYPE_GUILDCOMBATUSERSTATE		(BYTE)0xbf

#define	SNAPSHOTTYPE_PLAYERPOS	(BYTE)0xc0
#define	SNAPSHOTTYPE_DESTPOS	(BYTE)0xc1
#define	SNAPSHOTTYPE_MOVERSETDESTOBJ	(BYTE)0xc2
#define	SNAPSHOTTYPE_DESTANGLE	(BYTE)0xc3
#define	SNAPSHOTTYPE_MOVINGACTMSG	(BYTE)0xc4
#define SNAPSHOTTYPE_SETACTIONPOINT	(BYTE)0xc5
#define SNAPSHOTTYPE_SETNAVIPOINT	(BYTE)0xc6
#define	SNAPSHOTTYPE_MOVERDEATH		(BYTE)0xc7
#define	SNAPSHOTTYPE_MOVERCORR	(BYTE)0xc8
#define	SNAPSHOTTYPE_MOVERCORR2	(BYTE)0xc9
#define	SNAPSHOTTYPE_MOVERMOVED	(BYTE)0xca
#define	SNAPSHOTTYPE_MOVERBEHAVIOR	(BYTE)0xcb
#define	SNAPSHOTTYPE_MOVERMOVED2	(BYTE)0xcc
#define	SNAPSHOTTYPE_MOVERBEHAVIOR2		(BYTE)0xcd
#define	SNAPSHOTTYPE_MOVERANGLE		(BYTE)0xce
#define	SNAPSHOTTYPE_SETMOVEPATTERN	(BYTE)0xcf

#define	SNAPSHOTTYPE_SHOUT	(BYTE)0xd0
#define	SNAPSHOTTYPE_PLAYMUSIC	(BYTE)0xd1
#define	SNAPSHOTTYPE_PLAYSOUND	(BYTE)0xd2
#define	SNAPSHOTTYPE_MODIFYMODE	(BYTE)0xd3

#define	SNAPSHOTTYPE_DOAPPLYUSESKILL	(BYTE)0xd7
#define	SNAPSHOTTYPE_COMMONSKILL		(BYTE)0xdd
#define	SNAPSHOTTYPE_STATEMODE		(BYTE)0xdf
#define	SNAPSHOTTYPE_MELEE_ATTACK	(BYTE)0xe0
#define	SNAPSHOTTYPE_MAGIC_ATTACK	(BYTE)0xe1
#define	SNAPSHOTTYPE_RANGE_ATTACK	(BYTE)0xe2
#define	SNAPSHOTTYPE_SP_ATTACK		(BYTE)0xe3
#define	SNAPSHOTTYPE_MELEE_ATTACK2	(BYTE)0xe4
#define SNAPSHOTTYPE_ENDSKILLQUEUE	(BYTE)0xe5

#define	SNAPSHOTTYPE_POSTMAIL	(BYTE)0xe6
#define	SNAPSHOTTYPE_REMOVEMAIL		(BYTE)0xe7
#define	SNAPSHOTTYPE_QUERYMAILBOX	(BYTE)0xe9

#define	SNAPSHOTTYPE_CRIME			(BYTE)0xea
#define SNAPSHOTTYPE_RESURRECTION	(BYTE)0xeb
#define SNAPSHOTTYPE_SHIP_ACTMSG	(BYTE)0xec
//(BYTE)0xed
//(BYTE)0xee
#define	SNAPSHOTTYPE_ADD_OBJ		(BYTE)0xf0
#define SNAPSHOTTYPE_DEL_OBJ		(BYTE)0xf1
#define SNAPSHOTTYPE_REPLACE		(BYTE)0xf2
//(BYTE)0xf3
#define SNAPSHOTTYPE_REMOVEALLSKILLINFULENCE	(BYTE)0xf4

#define SNAPSHOTTYPE_DISGUISE		(BYTE)0xf5
#define SNAPSHOTTYPE_NODISGUISE		(BYTE)0xf6
#define SNAPSHOTTYPE_TAG			(BYTE)0xf7

#define SNAPSHOTTYPE_REMOVESKILLINFULENCE	(BYTE)0xf8
//(BYTE)0xf9
#define SNAPSHOTTYPE_GUILD_BANK_WND		(BYTE)(0xFA)
#define SNAPSHOTTYPE_PUTITEMGUILDBANK	(BYTE)(0xEF)
#define SNAPSHOTTYPE_GETITEMGUILDBANK	(BYTE)(0xD4)
#define SNAPSHOTTYPE_GUILD_LOGO		(BYTE)0xfb				// 로고 
#define SNAPSHOTTYPE_GUILD_CONTRIBUTION	(BYTE)0xfc			// 공헌도 
#define SNAPSHOTTYPE_GUILD_NOTICE		(BYTE)0xfd			// 공지사항 
#define	SNAPSHOTTYPE_GUILD_AUTHORITY	(BYTE)0xfe			// 권한 변경 
#define SNAPSHOTTYPE_GUILD_PENYA		(BYTE)0xff			// 페냐 변경 
#define SNAPSHOTTYPE_GUILD_REAL_PENYA	(BYTE)(0xD5)		// 월급 받음
#define SNAPSHOTTYPE_GUILD_CHANGEJOBLEVEL	(BYTE)(0xD6)	// 레벨이나 직업이 바뀜
#define SNAPSHOTTYPE_GUILD_ADDVOTE		(BYTE)(0xD8)	// 투표가 추가됨 
#define SNAPSHOTTYPE_GUILD_MODIFYVOTE   (BYTE)(0xD9)	// 투표의 변경(제거, 종료, 투표함)
#define	SNAPSHOTTYPE_WAR	(BYTE)0xda	// 전쟁

#define	SNAPSHOTTYPE_WAR	(BYTE)0xda	// 전쟁



#define SNAPSHOTTYPE_REQUEST_GUILDRANK	(BYTE)(0xdb)

#define	SNAPSHOTTYPE_SEX_CHANGE		(BYTE)(0xdc)

#ifdef __V050322_CACHEQUEST
#define	SNAPSHOTTYPE_WORLDMSG		(BYTE)(0xde)
#endif //  __V050322_CACHEQUEST

////////////////////////////////////////////////////////////////////////////
//  ERROR define
////////////////////////////////////////////////////////////////////////////
#define	ERROR_ACCOUNT_EXISTS				100L
#define ERROR_INVALID_SERVICE_PLAYER		102L
#define ERROR_DUPLICATE_ACCOUNT				103L
#define ERROR_ILLEGAL_ACCESS				104L
#define ERROR_DUPLICATE_SLOT				105L
#define ERROR_SLOT_OUTOFRANGE				106L
#define	ERROR_ILLEGAL_VER					107L
#define	ERROR_OVERFLOW						108L
#define	ERROR_EXTERNAL_ADDR					109L
#define	ERROR_INVALID_CLOCK					110L
#define ERROR_INVALID_NAME_CHARACTER		111L
#define	ERROR_WARTIME						112L
#define ERROR_BLOCKGOLD_ACCOUNT				119L
#define ERROR_FLYFF_PASSWORD				120L	// 비밀 번호가 틀립니다.
#define ERROR_FLYFF_ACCOUNT					121L	// 잘못된 계정입니다.
#define ERROR_FLYFF_AUTH					122L	// 실명인증후 게임접속이 가능합니다
#define ERROR_FLYFF_PERMIT					123L    // 프리프는 12세 이상 이용가 이므로 게임접속을 할수 없습니다.
#define ERROR_FLYFF_NEED_AGREEMENT			124L	// 14세 미만 가입자 분들은 부모님 동의서를 보내주셔야
#define ERROR_FLYFF_NO_MEMBERSHIP			125L	// 웹에서 탈퇴한 계정입니다
#define ERROR_BILLING_INFO_FAILED			126L	// 빌링 정보 없음
#define ERROR_BILLING_DATABASE_ERROR		127L	// 빌링 DB 에러 
#define ERROR_BILLING_TIME_OVER				128L	// 빌링 사용시간 만료 
#define ERROR_BILLING_OTHER_ERROR			129L	// 빌링 기타 다른 에러 
#define ERROR_BILLING_DISCONNECTED			130L	// 서버 접속 해제
#define ERROR_TOO_LATE_PLAY					131L	// 태국 22시에서 06시까지만 플레이 가능합니다.
#define ERROR_IP_CUT						132L	// 해외에서 국내로 못들어옴
#define ERROR_FLYFF_DB_JOB_ING				133L	// 실시간 데이터 작업 유저		
#define ERROR_15SEC_PREVENT					134L	// 15초간 로그인 금지 
#define ERROR_15MIN_PREVENT					135L	// 15분간 로그인 금지 
#define ERROR_CERT_GENERAL					136L	// CERT 일반 오류 	

// Party
#define ERROR_NOLEADER						200L
#define ERROR_FULLPARTY						201L
#define ERROR_NOPARTY						202L
#define ERROR_DIFFRENTPARTY					203L
#define ERROR_DIFFERNTUSERNAME				204L
#define ERROR_NOTPARTYPOINT					205L
#define ERROR_NOTPARTYSKILL					206L
#define ERROR_NOTTARGET						207L
#define ERROR_NOTMAMBER						208L
#define ERROR_SAMLEADER						209L

// NOERR_XXX 와 ERROR_XXX 는 중복되면 안된다.
#define	NOERR_REGISTER_ACCOUNT				500L		
#define NOERR_LOGIN							501L


#define	ERROR_NODE_NOT_FOUND				1000L

////////////////////////////////////////////////////////////////////////////
//  QPS_ define
////////////////////////////////////////////////////////////////////////////
#define	QPS_GUILD_MASTER	(BYTE)0x00
#define	QPS_GUILD_MEMBER	(BYTE)0x01
#define	QPS_POST	(BYTE)0x02

typedef	struct	_runscriptfunc
{
	char	lpszVal1[1024];
	char	lpszVal2[1024];
	DWORD	dwVal1;
	DWORD   dwVal2;
	WORD	wFuncType;
	D3DXVECTOR3 vPos;
}	RunScriptFunc, *PRunScriptFunc;

#define	FUNCTYPE_ADDKEY			(WORD)0x0010
#define	FUNCTYPE_REMOVEKEY		(WORD)0x0011
#define	FUNCTYPE_SAY			(WORD)0x0012
#define	FUNCTYPE_ADDANSWER		(WORD)0x0013
#define	FUNCTYPE_SETMARK		(WORD)0x0014
#define	FUNCTYPE_GOMARK			(WORD)0x0015
#define	FUNCTYPE_EXIT			(WORD)0x0016
#define	FUNCTYPE_ENDSAY			(WORD)0x0017
#define	FUNCTYPE_CREATEGUILD	(WORD)0x0018
#define	FUNCTYPE_DESTROYGUILD	(WORD)0x0019
#define	FUNCTYPE_INITSTAT		(WORD)0x001a
#define	FUNCTYPE_SETNAVIGATOR	(WORD)0x001b
#define	FUNCTYPE_REMOVENAVIGATOR	(DWORD)0x001c
#define	FUNCTYPE_REMOVEALLKEY	(WORD)0x001d
#ifdef __V050322_CACHEQUEST
#define	FUNCTYPE_SAYQUEST		(WORD)0x001e
#endif
#define	FUNCTYPE_INITSTR		(WORD)0x0020
#define	FUNCTYPE_INITSTA		(WORD)0x0021
#define	FUNCTYPE_INITDEX		(WORD)0x0022
#define	FUNCTYPE_INITINT		(WORD)0x0023
#define	FUNCTYPE_QUERYSETPLAYERNAME	(DWORD)0x0024
#define	FUNCTYPE_QUERYSETGUILDNAME	(DWORD)0x0025

// port num
#define	PN_PATCHSRVR	1100
#define	PN_WORLDSRVR	2000
#define	PN_CERTIFIER	23000
#define	PN_CORESRVR	4000
#define	PN_CACHESRVR	5400
#define	PN_DBSRVR_0		7000	// l
//#define	PN_DBSRVR_1		7100	// w
#define	PN_DBSRVR_1		24000	// w
#define PN_DBSRVR_2		7200	// core
#define	PN_LOGINSRVR	28000
#define	PN_PATCH_DISTRIBUTOR_0	9000
#define	PN_PATCH_DISTRIBUTOR_1	9100

#define	PN_MONITOR_0	11000
#define	PN_MONITOR_1	11001
#define	PN_MONITOR_2	11002

#define	PN_ACCOUNTSRVR_0	12000
#define	PN_ACCOUNTSRVR_1	12001

#define	PN_ACCUMULATOR		13000

#define	PN_ADBILL		29000


// PACKETTYPE_ADD_ACCOUNT의 리턴 코드
const BYTE ACCOUNT_DUPLIACTE     = 0;			// 중복 에러 
const BYTE ACCOUNT_CHECK_OK      = 1;			// 성공
const BYTE ACCOUNT_EXTERNAL_ADDR = 2;			// 허용되지 않는 주소 
const BYTE ACCOUNT_OVERFLOW      = 3;			// 인원초과
const BYTE ACCOUNT_BILLING_INFO_FAILED    = 4;	// 빌링 정보 없음 
const BYTE ACCOUNT_BILLING_DATABASE_ERROR = 5;	// 빌링 DB 에러 
const BYTE ACCOUNT_BILLING_TIME_OVER      = 6;	// 빌링 사용시간 만료 
const BYTE ACCOUNT_BILLING_OTHER_ERROR    = 7;	// 빌링 기타 다른 에러 
const BYTE ACCOUNT_BILLING_DISCONNECTED	  = 8;  // 빌링 서버가 끊겨 있는 경우
const BYTE ACCOUNT_IPCUT_ADDR	  = 9;  // 빌링 서버가 끊겨 있는 경우

const BYTE ACCOUNT_BILLING_WAIT_ACK	      = 128;  // 빌링응답을 기다리는 경우 

//
// m_cbAccountFlag의 의미 
//
const BYTE ACCOUNT_FLAG_18           = 0x01;		// 18세이상 
const BYTE ACCOUNT_FLAG_SCHOOLEVENT  = 0x02;		// 학교대항전 이벤트 참가가능자?
const BYTE ACCOUNT_FLAG_UNREGISTER18 = 0x04;		// 미등록 성인 
const BYTE ACCOUNT_FLAG_HANGAME		 = 0x08;		// 한게임 사용자


#define CHATTING_ENTERMEMBER		(BYTE)0x00
#define CHATTING_NEWCHATTING		(BYTE)0x01
#define CHATTING_DELETECHATTING		(BYTE)0x02
#define CHATTING_REMOVEMEMBER		(BYTE)0x03
#define CHATTING_CHATTING			(BYTE)0x04
#define CHATTING_CHATTINGROOMSTATE	(BYTE)0x05

#define GAME_RATE_SHOPCOST		(BYTE)0x00
#define GAME_RATE_ITEMDROP		(BYTE)0x01
#define GAME_RATE_GOLDDROP		(BYTE)0x02
#define GAME_RATE_MONSTEREXP	(BYTE)0x03
#define GAME_RATE_MONSTERHIT	(BYTE)0x04
#define GAME_RATE_X3			(BYTE)0x05	// GAME_RATE_ITEMDROP, //GAME_RATE_GOLDDROP, //GAME_RATE_MONSTEREXP
#define GAME_RATE_REBIRTH		(BYTE)0x06
#define GAME_RATE_HITPOINT		(BYTE)0x07
#define GAME_RATE_AGGRESSIVE	(BYTE)0x08
#define GAME_RATE_RESPAWN		(BYTE)0x09

const BYTE COMMONPLACE_ACTION	= 0x00;
const BYTE COMMONPLACE_ALPHA	= 0x01;

//현상금 처리관련 
const BYTE CT_WANTED_REQ_LIST   = 0x00;		// Core->Trans 리스트 요청 
const BYTE CT_WANTED_SET		= 0x01;		// Core->Trans 현상금 설정 

const BYTE ADD_PLAYER_ENEMY  = 0x00;		// 플레이어 적 추가 
const BYTE DEL_PLAYER_ENEMY  = 0x01;		// 플레이어 적 제거 
#endif //__MSGHDR_H__






















