//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BetaPatchClient.rc
//
#define LANG_KOR                        0
#define IDS_REINSTALL                   1
#define LANG_ENG                        1
#define IDR_RT_MANIFEST1                1
#define IDS_OUTOFSERVICE                2
#define LANG_JAP                        2
#define IDS_RUNNING_NEUZ                3
#define LANG_CHI                        3
#define IDS_RUNNING_PATCH               4
#define LANG_THA                        4
#define IDS_OPTION                      5
#define LANG_TWN                        5
#define IDS_CLOSE                       6
#define LANG_GER                        6
#define IDS_RESOLUTION                  7
#define LANG_SPA                        7
#define IDS_VIEW                        8
#define LANG_FRA                        8
#define IDS_TEXTURE                     9
#define LANG_POR                        9
#define IDS_SHADOW                      10
#define LANG_VTN                        10
#define IDS_OBJECTDETAIL                11
#define LANG_RUS                        11
#define IDS_FAR                         12
#define IDS_MEDIUM                      13
#define IDS_NEAR                        14
#define IDS_HIGH                        15
#define IDS_LOW                         16
#define IDS_DIRECTX_INSTALL             17
#define IDS_UPDATE_PATCH                18
#define IDS_RETRY                       19
#define LANG_FWC                        19
#define CNTRY_USA                       20
#define CNTRY_PHI                       21
#define CNTRY_TWN                       22
#define CNTRY_HK                        23
#define CNTRY_IND                       24
#define CNTRY_FWC                       30
#define IDC_BITMAP_OPTION00             101
#define IDD_BETAPATCHCLIENT_DIALOG      102
#define IDC_BITMAP_OPTION01             102
#define IDC_BITMAP_MAIN                 104
#define IDC_BITMAP_OPTION               105
#define IDC_BITMAP_MAIN_2               106
#define IDR_MAINFRAME                   128
#define IDD_MESSAGEBOX                  129
#define IDB_BACKIMAGE                   135
#define IDB_Message                     148
#define IDD_OPTION                      149
#define IDB_BITMAP1                     151
#define IDB_BITMAP2                     153
#define IDB_BITMAP3                     154
#define IDB_BITMAP4                     155
#define IDB_BITMAP5                     156
#define IDB_BITMAP3_MASK                157
#define IDB_BITMAP4_MASK                158
#define IDB_BITMAP5_MASK                159
#define IDB_BITMAP_OPTION               160
#define IDB_BITMAP_OPTION_MASK          161
#define IDB_BITMAP_OK1                  162
#define IDB_BITMAP_EXIT1                163
#define IDB_BITMAP_EXIT2                164
#define IDB_BITMAP_OPTIONIN             166
#define IDB_BITMAP_OPTIONOUT            167
#define IDB_BITMAP_STANDIN              168
#define IDB_BITMAP_STANDOUT             169
#define IDB_BITMAP_TESTIN               170
#define IDB_BITMAP_TESTOUT              171
#define IDB_BITMAP_OKIN                 172
#define IDB_BITMAP_OKOUT                173
#define IDB_BITMAP_CANCELIN             174
#define IDB_BITMAP_CANCELOUT            175
#define IDC_CURSOR1                     176
#define IDB_BITMAP6                     180
#define IDB_BITMAP6_MASK                181
#define IDB_BITMAP_BACK00_00            183
#define IDB_BITMAP_BACK00_01            184
#define IDB_BITMAP_OK00                 185
#define IDB_BITMAP_OK01                 186
#define IDB_BITMAP_CANCEL00             187
#define IDB_BITMAP_CANCEL01             188
#define IDB_BITMAP_CLOSE00              189
#define IDB_BITMAP_CLOSE01              190
#define IDB_BITMAP_START00              194
#define IDB_BITMAP_START01              195
#define IDB_BITMAP_TESTSERVER00         196
#define IDB_BITMAP_TESTSERVER01         197
#define IDB_BITMAP_OPTION00             202
#define IDB_BITMAP_OPTION01             203
#define IDB_BITMAP_BACK01_00            204
#define IDB_BITMAP_BACK01_01            205
#define IDB_BITMAP_BACK00_JAP           206
#define IDB_BITMAP_BACK01_JAP           207
#define IDB_BITMAP_BACK00_THA           220
#define IDR_MAINFRAME2                  221
#define IDD_DIALOG1                     222
#define IDD_DIALOG_FRAME                222
#define IDD_DIALOG2                     223
#define IDR_PNG1                        225
#define IDR_PNG2                        228
#define IDC_FILEPROGRESS                1001
#define IDC_TOTALPROGRESS               1002
#define IDC_OPTION                      1004
#define IDC_FILE_NUMBER                 1005
#define IDC_PATCHNOTES                  1006
#define IDC_DOWN_SPEED                  1007
#define IDC_CURRENT_STATE               1008
#define IDC_Msg2                        1009
#define IDC_Msg1                        1010
#define IDC_EXIT                        1011
#define IDC_MINIMIZE                    1012
#define IDC_MASQUERADEVERSION           1013
#define IDC_HOME                        1015
#define IDC_HOME2                       1016
#define IDC_RES_COMBO                   1017
#define IDC_TQ_RADIO1                   1018
#define IDC_TQ_RADIO2                   1019
#define IDC_BUTTON_START                1019
#define IDC_TQ_RADIO3                   1020
#define IDC_BUTTON_START2               1020
#define IDC_BUTTON_START_DISABLE        1020
#define IDC_VIEW_RADIO1                 1021
#define IDC_VIEW_RADIO2                 1022
#define IDC_VIEW_RADIO3                 1023
#define IDC_OD_RADIO1                   1027
#define IDC_OD_RADIO2                   1028
#define IDC_OD_RADIO3                   1029
#define IDC_SHD_RADIO1                  1030
#define IDC_SHD_RADIO2                  1031
#define IDC_SHD_RADIO3                  1032
#define IDC_STATIC2                     1034
#define IDC_STATIC3                     1035
#define IDC_HOME3                       1035
#define IDC_STATIC4                     1036
#define IDC_STATIC5                     1037
#define IDC_BUTTON1                     1038
#define IDB_BITMAP_REGISTER00           1039
#define IDB_BITMAP_REGISTER01           1040
#define IDC_BUTTON_REGISTER             1041
#define IDS_STR_FRA_SEARCHLIST          1042
#define IDS_STR_FRA_PATCHCOMP           1043
#define IDS_STR_FRA_RUN                 1044
#define IDS_STR_FRA_PATCHPROCESS        1045
#define IDS_STR_FRA_DOWNLOADING         1046
#define IDS_STR_FRA_DECOMPRESS          1047
#define IDS_STR_POR_PATCHCOMP           1048
#define IDB_BITMAP_MINIMIZE00           1049
#define IDB_BITMAP_MINIMIZE01           1050
#define IDB_BITMAP_START_D00            1051
#define IDB_BITMAP_START_D01            1052
#define IDB_BITMAP_PATCHNOTES00         1053
#define IDB_BITMAP_PATCHNOTES01         1054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        229
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
